### ISSUE TITLE
[FEATURE] Upgrade to Django 4.2 or 5.0

### ISSUE THREAD

**Issue by swainn** [tethysplatform/tethys#1001]
**Is your feature request related to a problem? Please describe.**
Django 3.2 will reach the end of life at the end of April 2024.

**Describe the solution you'd like**
Upgrade to Django 4.2 or 5.0 - possibly with a flexible pin to allow either to be used.

If this can be done without making breaking changes to Tethys, release in 4.X series, otherwise release in 5.0

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by swainn** [comment]
One idea would be to modify Tethys to work with multiple versions of Django so users could fall to 3.2 if they are using a feature that breaks. We could possibly do this with a modified version of the optional_dependencies functionality that would allow for checking not only if a package is installed, but what version is installed.

**Comment by sdc50** [comment]
I've been testing with Django 4.2. Here are my findings so far:

- The following packages could not be installed from conda-forge with django 4.2
  - django-simple-captcha (4.2 compatible version on pip)
  - django-recaptcha2 (looks like it's not being maintained - last release was in 2019)
  - django-analytical (conda package 3.1 only compatible with django 3.2 - pip package 3.1 seems to work)
- the url `resolve` function seems to have changed what is returned by the `func` attribute.
  - several changes needed in tests nowhere else
- Something changed with models that the Condor stuff didn't like. A few changes seems to handle it, however, we should look at deprecating some of that code.

I haven't yet tried testing against Django 5.0 or against Django 3.2  with the modifications. I think with some conda feedstock work we could get `django-simple-captcha` and `django-analytical` working, but I'm afraid `django-recaptcha2` might be a goner, which may mean we need to look at Tethys 5.0.
