### ISSUE TITLE
[FEATURE] Local logo URL for proxy app icon

### ISSUE THREAD

**Issue by ckrew** [tethysplatform/tethys#1010]
**Is your feature request related to a problem? Please describe.**
Proxy app allows for logo urls to be http endpoints but not local pngs.

**Describe the solution you'd like**
It would be nice if users could specify local pngs for proxy apps, like they can do for tethys apps.

**Comment by ckrew** [comment]
@swainn Looking into this and I wonder if the main reason this wasn't implemented initially was because the proxyapp metadata is all contain within the database without any file footprint. In other words, there is no app workspace or any file location to store a png like there is for tethysapps. 

Any thoughts on how to implement? If there is a general tethys workspace, we could create a proxy app folder there. We would also read the image file and store it in the DB but that might not be ideal for size reasons.

**Comment by swainn** [comment]
@ckrew that is a good point. One scenario where this may be applicable would be when a Tethys extension is used to install a Theme for a portal. The Tethys extension has it's own public/static directory where images and other static files can be stored. This could be used as a location for custom proxy app images.

Of course, in a production installation, a portal admin could add images to any of the existing static files directories after they have been collected for this purpose. This is not ideal, but manageable, especially if automated in a container. We've also talked about adding a way to upload images for use in cases like these...
