### ISSUE TITLE
[BUG] Production Installation not working with Daphne 4.1

### ISSUE THREAD

**Issue by sdc50** [tethysplatform/tethys#1032]
It appears there's an issue with the latest Daphne release (4.1) that prevents it from working in production (when used with Apache/Nginx).

See this this issue for a workaround.

https://github.com/django/daphne/issues/506

Unless this gets fixed soon, we should pin Daphne to 4.0 before releasing Tethys 4.3.

**Comment by swainn** [comment]
Fixed in 4.1.1

**Comment by swainn** [comment]
@sdc50 can you verify this works now?
