### ISSUE TITLE
[BUG] Issue with MULTIPLE_APP_MODE=False after logging out

### ISSUE THREAD

**Issue by swainn** [tethysplatform/tethys#1042]
**Describe the bug**
We encountered error after logging out single app mode:

![no_home_error](https://github.com/tethysplatform/tethys/assets/5123221/5bac3a8b-2cc9-4251-b3f6-b9edc6f19d15)

We then tried to manually go back to the root URL, which redirected to login and produced this error:

![image (6)](https://github.com/tethysplatform/tethys/assets/5123221/5e1e92b7-c8ee-4e43-9b28-8ab6ebd01aea)

It seems to be looking for a `home` view that doesn't exist.

**To Reproduce**
1. Setup a portal with single app mode
2. Login
3. Logout

**Expected behavior**
We should be able to login after logging out

**Errors/Traceback**
See above.

**Screenshots**
See above.

**Comment by ckrew** [comment]
@swainn What app was installed when this happened? I can take a look

**Comment by swainn** [comment]
It's our Loone app. Might have to do with the app not having a `home` controller:

![image](https://github.com/tethysplatform/tethys/assets/5123221/e601dd06-ef1c-4e0d-abe7-16151e62c342)

**Comment by swainn** [comment]
I confirmed that changing the index URL and controller to “home” fixes the issue. Tethys should get those dynamical from the app class I think.
