### ISSUE TITLE
Docs Typo

### ISSUE THREAD

**Issue by swainn** [tethysplatform/tethys#108]
On the page: http://tethys-platform.readthedocs.org/en/1.1.0/installation/web_admin_setup.html

Section 2d, it says:

“Execute the following command in the terminal to determine the endpoint for the built-in GeoServer:”

It should say:

“Execute the following command in the terminal to determine the endpoint for the built-in 52North:”

**Comment by ezrajrice** [comment]
This is showing up as already being fixed on my end. @swainn Nathan, did you do this?

**Comment by swainn** [comment]
I don't remember. But I have confirmed that it is fixed.
