### ISSUE TITLE
Dockerize Tethys Portal

### ISSUE THREAD

**Issue by swainn** [tethysplatform/tethys#110]
Create a Docker for Tethys Portal that can be used for development and hosting. This will have several advantages:
- Eliminate the differences between development environment and hosting environment
- Easier deployment
- Easier to scale

**Comment by rfun** [comment]
@swainn  : Could you please give me contributor access or assign me this issue?

**Comment by swainn** [comment]
Done.

**Comment by rfun** [comment]
@swainn  : Yep you are right :) Thanks for the invite

**Comment by swainn** [comment]
Tethys Platform has had a Dockerfile for some time and has an official Docker image on Dockerhub that is updated with each release: https://hub.docker.com/r/tethysplatform/tethys-core
