### ISSUE TITLE
Gizmo attributes with spaces

### ISSUE THREAD

**Issue by swainn** [tethysplatform/tethys#114]
Adding attributes to gizmos does not allow for attributes with spaces because the quotes are removed when passing to template.

**Comment by swainn** [comment]
For example if you use attributes to add the class attribute with multiple classes:

attributes='class="foo bar"'

it doesn't work because the quotes are dropped in the process. It results in something like this:

<elem class="foo" bar>

**Comment by ezrajrice** [comment]
Nathan,

Could you point me to the code that handles this. I can't find it and don't
want to waste a bunch of time trying to search for it.

Thanks
Ezra

**Comment by swainn** [comment]
Sure thing. The "attributes" property is inherited from the `TethysGizmoOptionBases <https://github.com/tethysplatform/tethys/blob/master/tethys_gizmos/gizmo_options/base.py#L12>`_ class.

**Comment by swainn** [comment]
See this thread on the forum for a specific example of this bug: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/tethysplatform/3_AGvbj3cUc

The double quotes are not preserved during the gizmo rendering process.

**Comment by ezrajrice** [comment]
Closed. I accidentally forgot to branch off of master and instead branched off of dev. This has been merged to dev.
