### ISSUE TITLE
Implement the HydroShare Python Social Auth backend

### ISSUE THREAD

**Issue by swainn** [tethysplatform/tethys#116]
Need a custom Python Social Auth backend to support OAuth2 with HydroShare. A skeleton class has been created in:

tethys_services.backends.hydroshare.HydroShareOAuth2

Once HydroShare has a functioning OAuth2 services, modify this class appropriately to enable the OAuth2 support. All other machinery should be in place.

**Comment by ezrajrice** [comment]
This is in progress. I am working with Rob to fix the "Mismatched_Redirect_URI" error. We seem to be close to finishing this up.

**Comment by ezrajrice** [comment]
I am just waiting for some parameter explanations for the documentation. After that, this will be closed.

**Comment by swainn** [comment]
Be sure to take the TODO out of the doc string.

**Comment by swainn** [comment]
https://github.com/hydroshare/hydroshare/wiki/HydroShare-REST-API#oauth-20-support

**Comment by ezrajrice** [comment]
closed
