### ISSUE TITLE
The height and width parameters don't work on d3 gizmos

### ISSUE THREAD

**Issue by swainn** [tethysplatform/tethys#129]
Fix the d3 plot view gizmos to use the height and width supplied by the user. Also, make width adjust dynamically with window resizes if it is set to 100%.

![image](https://cloud.githubusercontent.com/assets/5123221/9238060/b9e518d2-410c-11e5-834e-8175807f1663.png)

**Comment by ezrajrice** [comment]
fixed with as of commit # 106092104b5a328b166d7f3b4444b83dc4745a13
see hotfix 1.2.1
