### ISSUE TITLE
Tutorial documentation - persistent stores

### ISSUE THREAD

**Issue by sdc50** [tethysplatform/tethys#132]
Update the tutorial documentation to reflect the new way of getting persistent stores through the app class rather than through utilities.

See https://groups.google.com/forum/#!topic/tethysplatform/_Oh-PddhQus

**Comment by swainn** [comment]
I thought I had done that...
On Wed, Aug 19, 2015 at 4:39 PM sdc50 <notifications@github.com> wrote:

> Update the tutorial documentation to reflect the new way of getting
> persistent stores through the app class rather than through utilities.
>
> See https://groups.google.com/forum/#!topic/tethysplatform/_Oh-PddhQus
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tethysplatform/tethys/issues/132>.
>
-- 
Nathan Swain
