### ISSUE TITLE
SELinux Troubleshooting Suggestion

### ISSUE THREAD

**Issue by snowman2** [tethysplatform/tethys#136]
# SELinux Troubleshooting
## Step 1: Set in permissive mode
```
$ setenforce 0
```
## Step 2: Give permissions to process
If you don’t have audit2allow:
https://bugzilla.redhat.com/show_bug.cgi?id=879812
```
$ yum install policycoreutils-devel
```
Check permissions messages:
```
$ audit2allow –w –a
```
Read the message and make smart decisions! Loop!

Read:
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Security-Enhanced_Linux/sect-Security-Enhanced_Linux-Fixing_Problems-Allowing_Access_audit2allow.html

https://wiki.centos.org/HowTos/SELinux

Example of some things I needed to do:
```
$ setsebool -P httpd_can_network_connect 1
$ setsebool -P httpd_can_network_connect_db 1
$ setsebool -P httpd_read_user_content 1
$ setsebool -P httpd_execmem 1
```
## Step 3: Set in enforcing mode and check to see if it works
```
$ setenforce 1
```
If it fails, go back to step 1

## Step 4: If it works, make enforcing mode permanent
```
$ setenforce 1
$ vim /etc/seliniux/config
```
make sure mode is enforcing

**Comment by sdc50** [comment]
This issue will be addressed by issue #146
