### ISSUE TITLE
Normalizing References to Controllers

### ISSUE THREAD

**Issue by sdc50** [tethysplatform/tethys#139]
The way that controllers are referenced should be the same for UrlMaps and for HandoffHandlers.

Currently UrlMaps take the form: 'app_package.module.controller', while HandoffHandlers take the form: 'module:controller'. 

They way these are specified should be made consistent.

**Comment by sdc50** [comment]
The way controllers are specified in other Django functions is also inconsistent. It would be nice if we could abstract this to make it consistent everywhere.

**Comment by swainn** [comment]
I think the best format would be dot notation. No colons.

**Comment by swainn** [comment]
This also needs to be done in persistent stores.

**Comment by swainn** [comment]
Is this done? Have we updated the documentation on this?

**Comment by sdc50** [comment]
Yes, this was documented.

**Comment by sdc50** [comment]
Although, it looks like the spatial persistent store documentation didn't get update. I'll take care of that.
