### ISSUE TITLE
Don't have to logout and login again

### ISSUE THREAD

**Issue by snowman2** [tethysplatform/tethys#140]
http://docs.tethysplatform.org/en/latest/installation/linux.html#finish-the-docker-installation

In part b, if you replace:
```
$ gnome-session-quit --logout
```
with:
```
$ newgrp
```
Then you don't need part c. It does that process for you.

**Comment by swainn** [comment]
Test and confirm that it works before changing in docs.

**Comment by swainn** [comment]
Change back to:

$ gnome-session-quit --logout

**Comment by swainn** [comment]
@ezrajrice, did you ever fix this?

**Comment by ezrajrice** [comment]
@swainn 
This got changed from version 1.3 to 1.4, so I did not do anything with this. Does the documentation just need to be changed back to the old version of 

$ gnome-session-quit --logout

**Comment by ezrajrice** [comment]
Updated and merged with dev.
