### ISSUE TITLE
Formalize an app.ini for each app

### ISSUE THREAD

**Issue by swainn** [tethysplatform/tethys#148]
As a step toward having admins assign settings to apps (like geoservers, ckan servers, etc) Create and app.ini with formal settings (controlled vocabulary) that would allow Tethys admins that are installing apps to assign the geoservers to the app for use.

How to handle case where app wants to use multiple geoservers/datastores.

**Comment by swainn** [comment]
Add a get_assigned_geoservers()

**Comment by sdc50** [comment]
This issue is being superseded by issue #123.
