### ISSUE TITLE
Update less files to reflect style changes

### ISSUE THREAD

**Issue by sdc50** [tethysplatform/tethys#151]
Update the less files to reflect the style changes that were made as part of commit 3ee991983c4d1a1b1ea1c5ebfc4f3063e6a42c1c.

**Comment by sdc50** [comment]
Make sure to correct the padding-right of the actions area. (This was changed from 350 to 300 but it shouldn't have been changed). I just need to be sure to not change this in the less file.

**Comment by sdc50** [comment]
Also, move the javascript function to a utilities file and import it in the map gizmo.

**Comment by swainn** [comment]
I already created a utilities file and moved the function there, so that is done.
