### ISSUE TITLE
Dataset service registration doesn't allow https

### ISSUE THREAD

**Issue by sdc50** [tethysplatform/tethys#159]
When registering a dataset through the Tethys admin it is invalid to list any endpoint that does not start with http://. This means that an endpoint starting with https:// is invalid. This should be modified to allow for both http and https.

**Comment by swainn** [comment]
I just submitted a fix to dev that fixes this on spatial dataset services last week. I think the change should carry over to endpoints on the other services like dataset services. I didn't do it as a hotfix though.

See: https://github.com/tethysplatform/tethys/blob/dev/tethys_services/models.py#L19

As a side note and somewhat related, I also added a way to specify a public endpoint in addition to the normal endpoint (which is assumed private now???). 

See: https://github.com/tethysplatform/tethys/blob/dev/tethys_services/admin.py

**Comment by sdc50** [comment]
I was on a different branch when I was testing, but looks like it's working
great on dev. I just edited the database directly on the demo server so I
don't think it's urgent enough to get this in as a hotfix. I'm not sure I
understand the need for a public and private endpoint. Can you give an
example?

On another side note and somewhat related, I think we have a bit of a
migration mess. I don't think you pushed the migration that added the
public endpoint fields. Also, I realized that there was some weird stuff
going on with the  compute migrations. I think I have it all sorted out
now, but it may require some tinkering to get your database synced up if
you've run syncdb recently and it created a compute migration.
