### ISSUE TITLE
Figure out the best way to handle migrations

### ISSUE THREAD

**Issue by swainn** [tethysplatform/tethys#160]
How can we manage the Django migrations effectively? Commit them all? Have end users generate their own? Some mix of this?

Perhaps this is a documentation issue. Do we just need to provide some troubleshooting to users on how to get past migration problems.

**Comment by sdc50** [comment]
I haven't looked into best practices for this at all, but I just had this idea for a workflow to handle migrations:

* During development don't commit migrations, we all just rerun syncdb as needed on the dev branch.
* Just before a new release someone is assigned to:
   * create a fresh database
   * apply all migrations on the master branch
   * switch to the dev branch and run makemigrations
   * commit all migrations made

I haven't thought through all of the implications of this, but for one it would require that we do a lot of merging migrations in our development environments if we have data we're trying to persist.

**Comment by swainn** [comment]
1. Install master (1.2)
2. Upgrade to frozen dev (1.3)
3. Make migrations
4. Commit the migrations that were generated as the official migrations.
