### ISSUE TITLE
Add an Initial Value parameter to select and select2 input gizmos

### ISSUE THREAD

**Issue by swainn** [tethysplatform/tethys#163]
The select/select2 gizmo has no way of specifying the initial value. This needs to be added.

**Comment by ezrajrice** [comment]
This is updated to dev using "initial" as a list parameter. Closed.

**Comment by swainn** [comment]
I don't see "initial" as one of the parameters in the constructor:

https://github.com/tethysplatform/tethys/blob/dev/tethys_gizmos/gizmo_options/select_input.py#L70

Also, the doc strings need to be updated and at least one of the examples needs to illustrate how to use initial. Are there changes that have not been pushed to dev?

**Comment by sdc50** [comment]
I saw Ezra make the changes so I'm guessing they just haven't been pushed
yet.

**Comment by ezrajrice** [comment]
I pushed and merged to dev. I also updated the docs and included an example
of using "initial" but am confused why it's not showing up. I will take a
look at it again today to try to figure it out.

**Comment by ezrajrice** [comment]
Turns out I accidentally created a new remote branch for this. I've fixed this and pushed to dev.
