### ISSUE TITLE
Investigate Bokeh as an alternative to D3 for plotting

### ISSUE THREAD

**Issue by swainn** [tethysplatform/tethys#165]
See: http://bokeh.pydata.org/en/latest/

**Comment by ezrajrice** [comment]
Bokeh is not a good alternative, but I am currently looking into Plotly.

**Comment by snowman2** [comment]
Bokey Gizmo Added: https://github.com/tethysplatform/tethys/pull/207

**Comment by sdc50** [comment]
Are we waiting until changes get merged into master (i.e. releases) before we close issues or can we close them once they are fixed in dev?

**Comment by swainn** [comment]
Good question. I'd say let's close them when we finish them. They may not get closed otherwise.
