### ISSUE TITLE
Error catching on URL loading is masking true errors

### ISSUE THREAD

**Issue by swainn** [tethysplatform/tethys#177]
The change of how urls are defined with function literals rather than strings in Django 1.9 means that the controllers are imported when Tethys loads all the urls from apps. There is some error catching that is being performed in the process that maps the Tethys app urls to Django urls that is meant to report more meaningful error messages for Tethys developers who aren't familiar with Django or the implementation of Tethys. Unfortunately, this error catching is somewhat ambiguous and is masking the true problems (usually import errors) that could be easily fixed if the original error and trace were reported. (See: https://groups.google.com/forum/#!topic/tethysplatform/7w6hFj2aG1c) 

Solution: either remove this error catching so the default exceptions are raised or include the original text of the exception and the trace in the more Tethys appropriate exceptions.

See: https://github.com/tethysplatform/tethys/blob/master/tethys_apps/utilities.py#L56-L63

**Comment by sdc50** [comment]
I fixed this bug on the Aquaveo branch.
