### ISSUE TITLE
The GeoServer spatial dataset service engine needs refactoring for efficiency and stability

### ISSUE THREAD

**Issue by swainn** [tethysplatform/tethys#180]
The spatial dataset services engine for GeoServer needs to be refactored in at least two ways:

1) It needs to handle catalog object creation more efficiently so that operations in loops don't repeatedly query the entire catalog to populate the catalog object (see _get_geoserver_catalog_object  https://github.com/tethysplatform/tethys_dataset_services/blob/master/tethys_dataset_services/engines/geoserver_engine.py#L122)

2) catalog.reloads() should be evaluated for removal and only used when absolutely necessary (perhaps only when developer explicitly calls a reload method) It is currently used in 9 different places. A catalog.reload() temporarily renders GeoServer unavailable each time it is called...

**Comment by snowman2** [comment]
+1

**Comment by ezrajrice** [comment]
+1

**Comment by swainn** [comment]
Recently merged the ATCore API with Tethys Dataset Service Geoserver engine, which addresses many of the efficiency issues.
