### ISSUE TITLE
MapView JS API documentation typo

### ISSUE THREAD

**Issue by sdc50** [tethysplatform/tethys#193]
Under the getMap() section of the JS API documentation for MapView the code snippet lists:

var ol_map = TETHYS_MAP_VIEW.map;

but it should have:

var ol_map = TETHYS_MAP_VIEW.getMap();

**Comment by snowman2** [comment]
I would recommend following format in DEV as it was fixed there:

http://docs.tethysplatform.org/en/dev/tethys_sdk/gizmos/map_view.html#tethys-map-view-getmap

**Comment by sdc50** [comment]
Right, thanks for pointing that out.
