### ISSUE TITLE
tethys syncstores app_name (in dev version it has to be done multiple times)

### ISSUE THREAD

**Issue by snowman2** [tethysplatform/tethys#194]
With the dev version, when installing and app I have to:

$ tethys syncstores app_name
It will fail, and then:
$ tethys syncstores app_name -r
and it will work.

Need to find better solution.

**Comment by swainn** [comment]
Same issue experienced by @zhiyuli. See: https://groups.google.com/forum/#!topic/tethysplatform/rxtkvz2j-T0

**Comment by swainn** [comment]
@zhiyuli, I just pushed a fix for this bug on dev and release-candidate-140-1. Please pull and verify.

**Comment by zhiyuli** [comment]
A quick test showed it works now! Thanks!

Drew
