### ISSUE TITLE
Message Box Variable Unclear

### ISSUE THREAD

**Issue by jlgutenson** [tethysplatform/tethys#196]
http://docs.tethysplatform.org/en/dev/tethys_sdk/gizmos/message_box.html?highlight=messagebox#tethys_sdk.gizmos.MessageBox

For the example, it would be useful to use a different name for the variable than message_box:

change:

{% gizmo message_box message_box %}

to:

{% gizmo message_box my_message_box %}

**Comment by swainn** [comment]
It is somewhat confusing. The other form of the first argument to the gizmo tag perhaps sheds some light and of course naming your options variable appropriately helps:

{% gizmo "message_box" message_box_options %}

The first argument is meant to be the name of the gizmo (quotes optional) and the second argument is meant to be the options object that configures the gizmo. 

This is documented here: http://docs.tethysplatform.org/en/latest/tethys_sdk/gizmos.html#insert-the-gizmo

Of course the changes that @snowman2 and @sdc50  are working on will provide a third form of the gizmo tag, where the first argument can be omitted (it figures out the gizmo type from the options object):

{% gizmo message_box_options %}

I think this will clear up any confusion.

PS - Roll Tide!
