### ISSUE TITLE
Upgrade Python Social Auth

### ISSUE THREAD

**Issue by sdc50** [tethysplatform/tethys#201]
The Python Social Auth repository has been deprecated and is now spit into several repositories. Tethys needs to update it's code to work with the new repos that are actively maintained.

See: https://github.com/omab/python-social-auth/blob/master/MIGRATING_TO_SOCIAL.md

**Comment by swainn** [comment]
Note: This is now merged with dev. For production installations upgrading to this, I would recommend following the database migration approach described here: https://github.com/omab/python-social-auth/blob/master/MIGRATING_TO_SOCIAL.md
