### ISSUE TITLE
Jobs Table button booleans not being honored on update

### ISSUE THREAD

**Issue by ezrajrice** [tethysplatform/tethys#202]
I'm trying to remove the 'delete' button from the JobsTable gizmo using the boolean delete_btn=False, but it only removes the column space in the header row without preventing the button itself from being created and displayed. Am I using this gizmo incorrectly?

# CONTROLLER
jobs_table_options = JobsTable(
        jobs=filtered_jobs,
        column_fields=('id', 'name', 'creation_time', 'execute_time', 'run_time'),
        hover=True,
        striped=False,
        bordered=False,
        condensed=False,
        delete_btn=False
    )

**Comment by sdc50** [comment]
@ezrajrice can you confirm that this is working now?

**Comment by sdc50** [comment]
@ezrajrice I'm closing this issue because I believe that the merge request #218 fixed it. Let me know if you still are having issues with it.
