### ISSUE TITLE
Fix Modal CSS Styling

### ISSUE THREAD

**Issue by sdc50** [tethysplatform/tethys#217]
Pull request #211 added a template block for adding modals. By putting modals here the modal will cover the whole page and give the intended behavior of disabling everything until the modal is dismissed (does anyone disagree that this is the intended behavior?). 

However, because of some css styling that is added by the gizmos, the modal has a large right margin pushing the modal from center to the left (see screenshot):

![image](https://cloud.githubusercontent.com/assets/6454472/22436499/f6a39a4e-e6e9-11e6-9b82-3724cdbd775f.png)

**Comment by sdc50** [comment]
I see two ways to fix this:

1. We make sure the gizmo css only applies to elements that are added by the gizmo (by adding a gizmo class to all of the elements for example)

2. We remove the custom styling for modals in the `tethys_gizmos.css` and ensure that the gizmo modals add their markup to the new after_app_content block.

I vote we go with the latter so that their intended behavior(?) of disabling everything including the nav panel (which they currently don't do) is preserved. However, the first solution brings up a philosophical question: should gizmo styling effect anything but the gizmos? Maybe that would be a better question to bring up on the forum.

By getting rid of the `padding-right` style (and moving a couple of other styes from `tethys_gizmos.css` to `tethys_main.css`) the modal would be centered in the window this this:

![image](https://cloud.githubusercontent.com/assets/6454472/22437145/7fd61eca-e6ec-11e6-8615-59fddf49179f.png)

I personally think it feels more visually balanced if the modal is centered over the app content area:

![image](https://cloud.githubusercontent.com/assets/6454472/22437248/f021f910-e6ec-11e6-90f8-6cde63e6763e.png)

This would require added a `padding-left` style and also adding some javascript to adjust the styling when the nav bar is hidden so we avoid this:

![image](https://cloud.githubusercontent.com/assets/6454472/22437265/05f132c4-e6ed-11e6-9837-c3c18d9beb66.png)

**Comment by sdc50** [comment]
On second thought, having the modal centered in the window regardless of wether the nav pane is open or not might be just fine, and would be less work than making it change with the nave pane visibility.

**Comment by swainn** [comment]
There is a way to do it without using JavaScript. There is a toggle class that is added either to the nav window/button or the app content class that can be trapped on for css styling for the nav open and closed states.
