### ISSUE TITLE
App database not updating

### ISSUE THREAD

**Issue by astraiophos** [tethysplatform/tethys#220]
When uninstalling an app the database does not sync immediately. The current workaround is to run the uninstall command, restart the server, then kill the server and reinstall/develop the app with the desired app.py changes.

Suggestion: Make the setup.py 'install' command syncstores to remove the need to restart the server before installing the new app with the app.py changes.

**Comment by swainn** [comment]
I think this is addressed with the new method for installing apps in Tethys 3: The `tethys install` command performs the sync with the database operation and also calls syncstores if a persistent store setting is configured during the installation.
