### ISSUE TITLE
Docs not Building Due to Conda Issue

### ISSUE THREAD

**Issue by swainn** [tethysplatform/tethys#232]
@sdc50 and @snowman2 the dev version of the docs is not building because of an issue with Conda.

http://readthedocs.org/projects/tethys-platform/builds/5088063/

See Also:

https://github.com/rtfd/readthedocs.org/issues/2651
https://github.com/conda/conda/issues/3448#issuecomment-280816176

**Comment by sdc50** [comment]
@swainn when you [say](https://github.com/rtfd/readthedocs.org/issues/2651) that you "attempted wiping" the environment, I assume you mean that on the RTD Versions page you clicked on the `Wipe` button, right? And that didn't fix anything? It kind of looks like we may just need to wait for RTD to upgrade their conda. I agree with fmaussion, though, that it is striking that not more people have been complaining about the issue.

**Comment by swainn** [comment]
RTD fixed this.
