### ISSUE TITLE
Alternative to pastescript

### ISSUE THREAD

**Issue by snowman2** [tethysplatform/tethys#262]
Pastescript has not been updated since 2015 and is not supported above 3.4. We need to find an actively developed alternative that supports python 2/3.

http://stackoverflow.com/questions/9356190/alternatives-to-python-pastescripts-paster-create

**Comment by swainn** [comment]
@snowman2 I agree. I've been wanting to replace this using the native Django templating language, but it will take some doing. We should add this issue as a potential 2.1 priority.
