### ISSUE TITLE
Tethys Dev Install Guide

### ISSUE THREAD

**Issue by mmbayles** [tethysplatform/tethys#271]
On the install page[ instructions for linux and mac](http://docs.tethysplatform.org/en/dev/installation/linux_and_mac.html) the default sign credentials are not easily found in the instructions. I would recommend stating the credentials in the main instruction area.

**Comment by sdc50** [comment]
@mmbayles thanks for pointing this out. I've added the default credentials in the documentation more explicitly in a PR that should be merged soon.
