### ISSUE TITLE
Tethys 2.0 HydroShare OAuth

### ISSUE THREAD

**Issue by kjlippold** [tethysplatform/tethys#290]
I'm trying to use HydroShare OAuth in Tethys 2.0, and I'm getting the following callback:

File "/tethys/src/tethys_apps/tethysapp/hydroshare_resource_creator/utilities.py",
line 1453, in get_o_auth_hs
token = request.user.social_auth.get(provider='hydroshare').extra_data['token_dict']
File "/tethys/miniconda/envs/tethys/lib/python2.7/site-packages/django/db/models/manager.py",
line 122, in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/tethys/miniconda/envs/tethys/lib/python2.7/site-packages/django/db/models/query.py",
line 387, in get
self.model._meta.object_name
DoesNotExist: UserSocialAuth matching query does not exist.

**Comment by swainn** [comment]
@zhiyuli are you aware of this issue? I believe this is something that you updated in this release.

**Comment by zhiyuli** [comment]
Nathan,

Yes. This issue is still on my todo list. I haven't had a chance working on
it yet. Will get it done as soon as I can.

Thanks
Drew

**Comment by swainn** [comment]
Fixed with #307
