### ISSUE TITLE
Tethys 2.0 persistent store service not working

### ISSUE THREAD

**Issue by amsainju** [tethysplatform/tethys#304]
I am going through the tutorial of the Tethys platform and I am currently in "Advance Concept"  Section 1.h (http://docs.tethysplatform.org/en/stable/tutorials/getting_started/advanced.html). I expected to see the "Persistent Store Service" (that I created according to section 1.g) in Home › Tethys Apps › Installed Apps › DAM Inventory : PERSISTENT STORE DATABASE SETTING -> PERSISTENT STORE SERVICE. But it is not showing up. I could not continue with the following examples since I am not being able to connect with the database. 
Could you please help me with this?
Thank you.

Regards,
Arpan Man Sainju

**Comment by swainn** [comment]
I was unable to reporoduce this problem. @amsainju mentioned that he was able to resolve this with a fresh installation of the app. Sounds like the app got corrupted somehow.
