### ISSUE TITLE
Solution Mismatch in Intermediate concept tutorial

### ISSUE THREAD

**Issue by amsainju** [tethysplatform/tethys#305]
In Tutorial(http://docs.tethysplatform.org/en/stable/tutorials/getting_started/intermediate.html) : Intermendiate Concept-> Section 7, a link to the solution on Github for the intermediate concept is povided. But, when I downloaded the solution, it did not contain any changes made in Intermediate concept tutorial.

**Comment by swainn** [comment]
You need to be sure to download/checkout the correct branch. For example, the beginner-solution branch contains the solution for beginner tutorial. The master branch contains the empty project at the start of the tutorial. Instructions for how to do this with the terminal are provided in the tutorial.
