### ISSUE TITLE
App has no attribute get_persistent_store_engine

### ISSUE THREAD

**Issue by kjlippold** [tethysplatform/tethys#328]
The Persistent Stores API documentation for Tethys 2.0 still references get_persistent_store_engine in a few places, but it looks like it's been replaced by get_persistent_store_database. Is that correct?

<img width="704" alt="screen shot 2018-01-23 at 3 54 17 pm" src="https://user-images.githubusercontent.com/27028728/35305200-ba15706c-0055-11e8-874a-9ad5a7d728f4.png">

**Comment by swainn** [comment]
Yes, that is correct. Here is the reference to the correct method in the code: https://github.com/tethysplatform/tethys/blob/release/tethys_apps/base/app_base.py#L745 Thank you for the heads up on the docs discrepancies.
