### ISSUE TITLE
typos in tethys_apps/base/app_base.py cause secondary errors

### ISSUE THREAD

**Issue by zhiyuli** [tethysplatform/tethys#336]
Two typos in file tethys_apps/base/app_base.py cause secondary errors when app-level db is not correctly configured.

![image](https://user-images.githubusercontent.com/10070599/37979618-45efc872-31a6-11e8-8c76-8081587bee6b.png)

https://github.com/tethysplatform/tethys/blob/1d5d472df9d1d5faf55b8863354eec4a42597aa3/tethys_apps/base/app_base.py#L894

https://github.com/tethysplatform/tethys/blob/1d5d472df9d1d5faf55b8863354eec4a42597aa3/tethys_apps/base/app_base.py#L937

**Comment by swainn** [comment]
This was fixed in #355 about 3 years ago.
