### ISSUE TITLE
Custom Permissions cause issues on a production installation

### ISSUE THREAD

**Issue by rfun** [tethysplatform/tethys#343]
Using custom permissions in an application as described [here](http://docs.tethysplatform.org/en/stable/tethys_sdk/permissions.html?highlight=custom%20permission ) causes app to loose sync with their data in the main tethys database. This is probably happening since each time the portal restarts, the applications are forced to re-register their custom permissions in the database. When 10 instances of the same application try and sync up to the database, they run into race conditions and thence some of them go out of sync leading to a corrupted dataset. 

This issue was discussed in Tethys Weekly Scrum on Friday, 20th July 2018.

**Comment by swainn** [comment]
@rfun This may be a bug that has been addressed in the development version. Can you pull the latest on master and see if it is still a problem?

**Comment by rfun** [comment]
Not an issue anymore.
