### ISSUE TITLE
Remove Deprecated Code

### ISSUE THREAD

**Issue by swainn** [tethysplatform/tethys#364]
* Job Templates
* Pre-App Settings service methods

**Comment by sdc50** [comment]
> * Pre-App Settings service methods

I'm not sure I know what this is referring to. My guess was this: https://github.com/tethysplatform/tethys/blob/master/tethys_apps/base/app_base.py#L1159-L1387

But it looks like this code is used by the app testing framework,  so I'm not sure if there is actually deprecated code that needs to be removed.

**Comment by swainn** [comment]
@sdc50 Those aren't the methods I was thinking of. Those are for creating persistent store services dynamically (at runtime) and they are integral to how we manage our model databases at Aquaveo.

I was thinking of the old accessor methods for getting the different Tethys Services (not using settings), but I don't see those methods there anymore.

Check out this search on "deprectated" in the repo: https://github.com/tethysplatform/tethys/search?q=deprecated&unscoped_q=deprecated

The only complication is that some of those have been deprecated in 3.0 and shouldn't be removed yet. We need to come up with a more formal way to handle deprecations. Like a decorator or something along those lines.

**Comment by swainn** [comment]
Fixed by #523
