### ISSUE TITLE
Docs build failing because dask is not found

### ISSUE THREAD

**Issue by sdc50** [tethysplatform/tethys#405]
I think we just need to add dask to the list of mocked modules in the docs `conf.py`. Can this be tacked on to PR #400?

**Comment by swainn** [comment]
Yup. You got it.

**Comment by swainn** [comment]
The docs are building again, but the version is still displaying as 2.0.4. Not sure why though.

Here's the successful build: https://readthedocs.org/projects/tethys-platform/builds/8697357/
