### ISSUE TITLE
Better Documentation on Databases/Services in Tethys

### ISSUE THREAD

**Issue by swainn** [tethysplatform/tethys#415]
* Review documentation for inconsistencies
* Add new tutorial that is focused on databases and services

**Comment by speleophysics** [comment]
I was trying to get an app working with the Postgis docker container and kept running into problems with failing user authentication on the Postgis database. Finally I tracked this down to the fact that you are now using a new Postgis docker container (see #446), which does not create the default users and passwords described in the documentation here: http://docs.tethysplatform.org/en/stable/supplementary/docker_testing.html or in the PGAdmin III tutorial. I just wanted to point these out as existing inconsistencies.  I presume that the Tethys platform works with this new Postgis container without the previously created default users, but I haven't yet gotten that far with testing. 

In case someone else runs into this problem, the correct default user/password in the new Postgis docker container is postgres/mysecretpassword, though you are also given a chance to set the password upon docker initialization.

**Comment by speleophysics** [comment]
Docs still reference get_persistent_store_engine() (#328) at least in a few places here: http://docs.tethysplatform.org/en/latest/tethys_sdk/tethys_services/persistent_store.html

**Comment by speleophysics** [comment]
I've been browsing the improved production installation docs, which have been really helpful. I did notice that they still refer to the old ciwater/postgis docker in the distributed configuration section. Should this be the new mdillon/postgis docker? I'm also not sure what, environmental variables might be required for the newer docker to work with tethys. Anything beyond the postgres user password?

**Comment by swainn** [comment]
@speleophysics we just posted an update to the documentation on Friday. This included updating the [Distributed Configuration documentation](http://docs.tethysplatform.org/en/latest/installation/production/additional/distributed.html#postgresql-with-postgis-docker-deployment). The new approach is to use mdillon/postgis and then create the database users and tables required using the tethys db command. Take a look and let met know what additional clarification is needed if any.

**Comment by speleophysics** [comment]
Finally had a chance to look at this. While I haven't actually tested it, this new documentation looks pretty clear to me.
