### ISSUE TITLE
installation 'latest' didn't work but stable did

### ISSUE THREAD

**Issue by john3641** [tethysplatform/tethys#430]
The "latest" instructions posted on the Tethys Platform website (i.e., at docs/tehtysplatform.org/en/latest...), which shows "last updated: April 2017" for the developer installation didn't work for me when trying to install on my Ubuntu 18.04.02 system within Oracle VM Box. I got "Pip install failed".  Also, when I tried to activate the tethys environment by entering "t", I got "t: command not found".  But using "stable" instructions posted at tethysplatform.org/en/stable... worked fine. 
 
I spent many attempts and hours, stumped as to why the installation using "latest" wasn't working.  I had installed on Ubuntu 18 (within Oracle VM) on another computer with ease weeks earlier.  Finally, I realized I was in the "latest" links instead of the "stable" links.  That was hard to realize because both the "stable" and the "latest" show April 2017 as last updated.  (I didn't notice that less prominently - to me, anyway - off in the left margin, it said "latest" instead of "stable").  I don't know if anyone else has had this problem, but would it be good to change the "last updated" date, and maybe put "see...for stable version" immediately following the date?

**Comment by swainn** [comment]
The instructions are identical, with the exception of the branch that it tells you to pull, which is dynamically populated. Thus they were both updated at the same time and have the same last updated date. As you have discovered, latest points to whatever the latest development version of Tethys is, which is not guaranteed to be stable. Stable points to the latest release version of Tethys. 

How did you end up on the documentation for latest? The Tethys documentation should automatically point you at stable.

**Comment by john3641** [comment]
I wish I could tell you how I ended up on "latest" links, but I certainly did not intend to.  I'm trying to get there now, but can't, unless I actually replace the word "stable" in the url with "latest".  But that's certainly not how I got there originally.

**Comment by swainn** [comment]
@john3641 I think I figured out the problem, or at least the suspect. The "Tutorials" link on the [Tethys home page](http://www.tethysplatform.org/) was pointing to tutorials in latest. So if you followed that link you would have ended up on latest. I've updated the website to point to stable now. Thanks for reporting!

**Comment by john3641** [comment]
Yes, that sounds like what I got caught in.  Thanks for your attentiveness.
