### ISSUE TITLE
Bootstrap v3.2.0 vulnerabilities

### ISSUE THREAD

**Issue by ezrajrice** [tethysplatform/tethys#433]
The current version of Bootstrap that is packaged with Tethys Platform contains five known cross-site scripting (XSS) vulnerabilities. Updating to version 3.4.1 or 4.3.1(latest) would fix these issues.
See [link](https://snyk.io/test/npm/bootstrap/3.2.0) for more details on the vulnerabilities.

**Comment by swainn** [comment]
Upgrading to 4: https://getbootstrap.com/docs/4.0/migration/

**Comment by swainn** [comment]
Addressed by #441
