### ISSUE TITLE
JQuery v1.11.1 vulnerabilities

### ISSUE THREAD

**Issue by ezrajrice** [tethysplatform/tethys#434]
The current version of JQuery that is packaged with Tethys Platform contains two known vulnerabilities. One cross-site scripting (XSS) vulnerability and one prototype pollution vulnerability. Updating to version 3.4.0 or 3.4.1 (latest) will fix these issues.
See [link](https://snyk.io/test/npm/jquery/1.11.1) for more details on the version 1.11.1 vulnerabilities.

**Comment by swainn** [comment]
Addressed by #441
