### ISSUE TITLE
Error when install on Windows from new conda package

### ISSUE THREAD

**Issue by gaoxiang123456789** [tethysplatform/tethys#457]
When I use this command :       conda create -n tethys -c tethysplatform/label/dev -c tethysplatform -c conda-forge tethysplatform.

There will be a  following error:

[Errno 2] No such file or directory: 'D:\\WORKsoftware\\Anaconda\\pkgs\\tethysplatform-3.0.0b2-py_0\\site packages\\tethys_gizmos\\static\\tethys_gizmos\\vendor\\highcharts \\exporting-server\\java\\highcharts-export\\highcharts-export-web\\target\\highcharts-export-web\\WEB-INF\\lib\\commons-beanutils-core-1.7.0.jar'

**Comment by swainn** [comment]
@gaoxiang123456789 the conda package for Tethys is still under development and very much experimental for Windows at this point. I'd recommend installing on Linux or Mac for the time being.
