### ISSUE TITLE
Tags shouldn't be set and list for each tag

### ISSUE THREAD

**Issue by rfun** [tethysplatform/tethys#468]
https://github.com/tethysplatform/tethys/blob/d40b7d4ed1cb51c571707340de4b74baa4bb58a4/tethys_apps/templatetags/tags.py#L24

The above line seems to run a set and list each time a tag is added to the tag_array. It's a minor thing, no biggie, but I would think that it would only need to run that once after all the tags have been put in the array.  I could be wrong :)

**Comment by swainn** [comment]
Fixed in #496
