### ISSUE TITLE
Fix django-guardian version on stable environment_py files

### ISSUE THREAD

**Issue by rfun** [tethysplatform/tethys#480]
Installing from the latest release will give an error as django-guardian's latest version (released sep 8th) required path from django.urls, which doesn't exist before django 2. Fixing the version to django-guardian=1.5.* does the trick. We probably want to update the stable environment files accordingly.

**Comment by rileyhales** [comment]
I also ran into this problem yesterday and ended up doing the same thing to fix it.

**Comment by swainn** [comment]
Just released a new version of Tethys: https://github.com/tethysplatform/tethys/releases/tag/2.1.6

Please verify.

**Comment by rileyhales** [comment]
I just tried a fresh install on an ubuntu virtual machine and it solved the problem. i could start the development server and install an app. looks good to me.
