### ISSUE TITLE
tethys on ubuntu: tethys gen portal_config  error

### ISSUE THREAD

**Issue by gaowudao** [tethysplatform/tethys#500]
After "conda create -n tethys -c tethysplatform/label/dev -c tethysplatform -c conda-forge tethysplatform" and "conda activate tethys" command in the terminal,  and "tethys gen portal_config" command conducted in the terminal,  then the error occured and as follow:

(base) gaoxiang@gaoxiang-VirtualBox:~$ conda activate tethys
(tethys) gaoxiang@gaoxiang-VirtualBox:~$ tethys gen portal_config
usage: tethys gen [-h] [-d DIRECTORY]
                  [--allowed-hosts ALLOWED_HOSTS [ALLOWED_HOSTS ...]]
                  [--client-max-body-size CLIENT_MAX_BODY_SIZE]
                  [--asgi-processes ASGI_PROCESSES] [--db-name DB_NAME]
                  [--db-username DB_USERNAME] [--db-password DB_PASSWORD]
                  [--db-host DB_HOST] [--db-port DB_PORT] [--db-dir DB_DIR]
                  [--production] [--open-portal] [--open-signup]
                  [--tethys-port TETHYS_PORT] [--overwrite]
                  [--add-apps ADD_APPS [ADD_APPS ...]] [--session-persist]
                  [--session-warning SESSION_WARNING]
                  [--session-expire SESSION_EXPIRE]
                  [--static-root STATIC_ROOT]
                  [--workspaces-root WORKSPACES_ROOT] [--bypass-portal-home]
                  [--add-quota-handlers ADD_QUOTA_HANDLERS [ADD_QUOTA_HANDLERS ...]]
                  [--django-analytical DJANGO_ANALYTICAL [DJANGO_ANALYTICAL ...]]
                  [--add-backends ADD_BACKENDS [ADD_BACKENDS ...]]
                  [--oauth-options OAUTH_OPTIONS [OAUTH_OPTIONS ...]]
                  [--channel-layer CHANNEL_LAYER] [--captcha]
                  [--recaptcha-private-key RECAPTCHA_PRIVATE_KEY]
                  [--recaptcha-public-key RECAPTCHA_PUBLIC_KEY]
                  {settings,asgi_service,nginx,nginx_service,portal,services,install,site_content}
**tethys gen: error:** argument type: invalid choice: 'portal_config' (choose from 'settings', 'asgi_service', 'nginx', 'nginx_service', 'portal', 'services', 'install', 'site_content')

**Comment by swainn** [comment]
@gaowudao can you please try installing again? I think the documentation updated before we released the corresponding version. It should be up now.
