### ISSUE TITLE
Repository is becoming bloated

### ISSUE THREAD

**Issue by sdc50** [tethysplatform/tethys#511]
I've noticed that cloning the repository is taking a long time. Currently a fresh clone is 309MB! I wonder if it's time to clean up a bit. This article describes the process of removing big files from you history: https://git-scm.com/book/en/v2/Git-Internals-Maintenance-and-Data-Recovery

Unfortunately it requires re-writing all the commits that have happened since the large files were committed. The other challenge is that it requires removing large files from the repo, and we currently still have a lot of large files in the repo. I think we need to take a look and see if there is another way to provide large data files so they don't end up bogging down our repository.

I started tracking down some of the largest files in the repo:

45M Jan  7 12:51 nwm_20200106_short_range_forecast.zip
 13M Jun  9  2017 highcharts-export-web.war
 21M Jul 22 12:00 tethys_gizmos/static/tethys_gizmos/cesium_models/*

The highcharts one is the most concerning since it's been in the repo for so long. It's not clear to me if it's actually needed. I suspect we don't actually use anything in the `tethys_gizmos/static/tethys_gizmos/vendor/highcharts/exporting-server/java/` directory.

**Comment by swainn** [comment]
@sdc50 I agree that we need to clean up the repo. I'm afraid I'm responsible for the nwm_20200106_short_range_forecast.zip file. It's part of the THREDDS tutorial. It would be nice if we had a place to host files that are used in tutorials or other parts of the documentation.

I imagine much of the bloat is due to the binary files that we have in the repo, which are mostly images in the documentation and static files. Anytime those files change, git essentially adds a new copy to the history since it can't diff them.

Some solutions we could look at for managing large files / binary files are:

git-lfs
git-media
git-annex

**Comment by swainn** [comment]
> The highcharts one is the most concerning since it's been in the repo for so long. It's not clear to me if it's actually needed. I suspect we don't actually use anything in the `tethys_gizmos/static/tethys_gizmos/vendor/highcharts/exporting-server/java/` directory.

I think that handles the exporting capabilities of highcharts, which we use in CityWater...

**Comment by swainn** [comment]
One final thought on this:

Our efforts to move to CDNs for 3rd-party dependencies should help with this. Someday, I'd like our git repository to have no 3rd-party code in it. We could also look at using npm or something similar and have the dependencies "installed" when Tethys is installed if we want to host locally still.

**Comment by swainn** [comment]
#767 makes it so that dependencies are either loaded via CDN or downloaded using `npm`, and thus will no longer need to be stored in the source code.

**Comment by swainn** [comment]
Even after eliminating our static dependencies, the documentation contains a lot of images (screenshots) that take up quite a bit of space. We should implement using `git-lfs` to store binary files so we only need to pull them when needed (like when working on docs).
