### ISSUE TITLE
Open Layers version discussed in the docs is not consistent

### ISSUE THREAD

**Issue by sdc50** [tethysplatform/tethys#520]
The tip at the bottom of the [Map View section](http://docs.tethysplatform.org/en/latest/tethys_sdk/gizmos/map_view.html) of the docs says that the current default version of open layers is 5.3.0. Later in the docs (http://docs.tethysplatform.org/en/latest/tethys_sdk/gizmos/map_view.html#javascript-api) it says that we are using OpenLayers 4.0.1. These should be consistent.

@swainn Can you fix this with the other docs changes that you are working on?

**Comment by swainn** [comment]
@sdc50 I'll add that to the list of things to fix.

**Comment by swainn** [comment]
Fixed in #519
