### ISSUE TITLE
tethys db configure fails

### ISSUE THREAD

**Issue by rileyhales** [tethysplatform/tethys#524]
I attempted to install tethys 3.0.0 using the "getting started" instructions on the documentation. Installing the package from conda succeeds and tethys gen portal_config succeeds. It fails on tethys db configure. The ~/.tethys/psql directory is created but it fails to create roles. None of the rest of the commands seem to work. Here's the terminal output from what i did, start to finish.

[Terminal Saved Output.txt](https://github.com/tethysplatform/tethys/files/4188229/Terminal.Saved.Output.txt)

**Comment by rileyhales** [comment]
i didn't specify this was on a mac OS version 10.15.3. I tried it on ubuntu and it works fine.

**Comment by swainn** [comment]
> Starting Postgresql database server in "/Users/rileyhales/.tethys/psql/data" on port 5436...
waiting for server to start.... stopped waiting
pg_ctl: could not start server

@rileyhales it looks like the database failed to start for some reason. What happens when you run `tethys db start`?

**Comment by swainn** [comment]
@rileyhales sorry, I see now that you attempted that in the log file. Let's start with baby steps and see if we can at least get the database running. Please run the following and share the result:

```
# Stop and remove the database
tethys db purge

# Initialize the database (no Tethys tables or users though)
tethys db init

# Start the database
tethys db start
```

**Comment by rileyhales** [comment]
So i did some trials on other macs in the BYU hydroinformatics lab. When i start on a mac thats never had tethys on it, create the environment, and run tethys db configure i get the same errors i shared earlier. If i run tethys db purge and then do tethys db configure then it succeeds and i can start the development server. Maybe installing the conda package brings some partially created db or settings, etc that get wiped out by tethys db purge which then makes tethys db configure work correctly.

i'll share some outputs when i get to work today and can produce some documentation. But for now it looks like the tethys db purge command needs to be run first although i dont know why.

**Comment by swainn** [comment]
@sdc50 have you experienced this on your mac?

**Comment by rileyhales** [comment]
i agree. I'm not sure what to think. The only idea i've thought up is maybe other db's i had  running that were interfering with it. That would make this an edge case and probably not an error with tethys. I originally was thinking that the file permissions were wrong somehow but since i made it run with tethys db configure after running purge, that makes me think its not that.

**Comment by swainn** [comment]
So the work around for now is:

```
# Stop and remove the database
tethys db purge

# Re-run configure
tethys db configure
```

**Comment by rileyhales** [comment]
Yes that sounds right to me. I've since been able to use tethys3 normally after that hurdle so i think i'd propose that we make a note of that in the "getting started" section of the docs. Or perhaps on the page that explains the tethys db command.
