### ISSUE TITLE
Settings Documentation for TETHYS_PORTAL_CONFIG is wrong

### ISSUE THREAD

**Issue by swainn** [tethysplatform/tethys#527]
The Portal Config Documentation suggests that a bunch of settings should be nested under ``TETHYS_PORTAL_CONFIG``, but that doesn't work see: http://docs.tethysplatform.org/en/stable/tethys_portal/configuration.html)

These settings should be set at the ``settings`` level. See: https://github.com/tethysplatform/tethys/blob/master/tethys_portal/settings.py#L71

**Comment by swainn** [comment]
This is fixed in #532

**Comment by rfun** [comment]
There might be one more change: In the example portal_config here : http://docs.tethysplatform.org/en/latest/tethys_portal/configuration.html the following settings are still listed as a sub section of TETHYS_PORTAL_CONFIG: 

BYPASS_TETHYS_HOME_PAGE
ENABLE_OPEN_SIGNUP
ENABLE_OPEN_PORTAL
TETHYS_WORKSPACES_ROOT
STATIC_ROOT

**Comment by swainn** [comment]
@rfun we just merged PR #573 this weekend that should address this issue. Both the nested approach and the non-nested approach should work. See updated documentation here: http://docs.tethysplatform.org/en/latest/tethys_portal/configuration.html
