### ISSUE TITLE
Login button style being overwritten

### ISSUE THREAD

**Issue by ezrajrice** [tethysplatform/tethys#538]
When scrolling down, the Login button on the home page changes background color to match the SECONDARY COLOR listed in portal config. In dev installation using Firefox, the button does not change back to its original background color on scrolling to the top. In production, the button seems to consistently change back to its original color. It seems that the button should be consistent with whatever colors are being used on the rest of the header since it is always on top as you scroll.

**Comment by swainn** [comment]
Care to submit a Pull Request?
