### ISSUE TITLE
Remove autocopy on click from Tethys Docs (v3.0)

### ISSUE THREAD

**Issue by rfun** [tethysplatform/tethys#541]
With the new docs, there is a feature that auto copies any code snippet. Many a time I only need a bit of the code snippet or a few lines, but instead anytime I click in there, it copies the whole thing, even if I select a bit and try copying that, it still gives me the entire snippet. 

I suggest that we remove auto copying on click, but still leave the copy button on the top left side so that one may copy the entire code if needed. 

Thoughts?

**Comment by rileyhales** [comment]
I agree. if this is possible with the docs template that is being used, i think it would be a good improvement.

**Comment by swainn** [comment]
I share your frustration. Unfortunately, the RTD theme that we are using doesn't provide an easy way to configure or change this. I'd recommend submitting an issue or PR to their github page:

https://github.com/bashtage/sphinx-material

**Comment by swainn** [comment]
As a work around I've found that if you select text the text without releasing the primary button, then right-click and release when your mouse is over the copy, it will copy only the text selected.
