### ISSUE TITLE
Example Dam Inventory app doesn't install

### ISSUE THREAD

**Issue by rfun** [tethysplatform/tethys#549]
I am trying to work with websockets and was wanting to get the following tutorial app installed and working on my local system. The tutorial page is  http://docs.tethysplatform.org/en/stable/tutorials/websockets.html

I cloned the repo, checked out the right branch and ran tethys install 

```
Loading Tethys Extensions...
Loading Tethys Apps...
Tethys Apps Loaded: warehouse, gw

Running application install....
Syncing the Tethys database with installed apps and extensions...
Loading Tethys Extensions...
Loading Tethys Apps...
Tethys Apps Loaded: warehouse, gw

Loading Tethys Extensions...
Loading Tethys Apps...
Tethys Apps Loaded: warehouse, gw

Portal install file found...Processing...
No apps configuration found in portal config file. Searching for local app level services.yml... 
No Services file found.
Running Interactive Service Mode. Any configuration options in services.yml or portal_config.yml will be ignored...
Hit return at any time to skip a step.
The app or extension you specified ("dam_inventory") does not exist. Command aborted.
No settings found for app "dam_inventory". Skipping interactive configuration...
Services Configuration Completed.
The app or extension you specified ("dam_inventory") does not exist. Command aborted.
```

I also tried running `python setup.py develop` manually and then running tethys install and it still didn't work. 
Not a critical bug, but it would be nice to have this tutorial app install and run so that we can follow along the documentation.

**Comment by swainn** [comment]
@rfun I was unable to reproduce this issue. It installed fine for me.

Do your warehouse and/or gw have an ``__init__.py`` in the ``tethysapp`` directory? If so, they will cause problems with apps that follow the new namespacing pattern (no ``__init__.py`` in the ``tethysapp`` directory). Make sure that the ``tethysapp`` directory of all apps **do not** have an ``__init__.py``.

For more information about this issue, see: https://packaging.python.org/guides/packaging-namespace-packages/.

Tethys has adopted Native Namespace Packages for apps.
