### ISSUE TITLE
decorator.py permission exception tests not working as expected

### ISSUE THREAD

**Issue by msouff** [tethysplatform/tethys#550]
https://github.com/tethysplatform/tethys/blob/891ddd608d17d1eac86621196196282a632c7c18/tests/unit_tests/test_tethys_apps/test_decorators.py#L166

The tests never hit line 195 of the tethys_apps/decorators.py. I think there should be separate tests to handle the 403 and the 404, and the DEBUG setting should be mocked. I tried to fix it quickly but couldn't.

@ezrajrice I think you were the one working on this, right.

**Comment by ezrajrice** [comment]
@msouff This issue is resolved with PR #547. I split that test into two so that it tests the response when DEBUG is True and when DEBUG is False. It just hasn't been merged yet.

**Comment by msouff** [comment]
Ahh nice. Good thing I didn't spent time trying to fix it :-D
