### ISSUE TITLE
Assign  Persistent Store service to Dam Inventory setting version 3.0

### ISSUE THREAD

**Issue by hello-deepak** [tethysplatform/tethys#570]
I was following the step 9 in Advance Tutorial
9. Assign  Persistent Store service to Dam Inventory.

http://docs.tethysplatform.org/en/stable/tutorials/key_concepts/advanced.html
as ![image](http://docs.tethysplatform.org/en/stable/_images/Assign_Persistent_Store_Service.png)

But in my persistent store database settings, I could not find primary_db to select dam_inventory.

![image](https://user-images.githubusercontent.com/7577697/86598924-9ce1f680-bfbd-11ea-8251-74995513e2be.png)

**Comment by swainn** [comment]
@hello-deepak please try uninstalling and reinstalling the app:

```
tethys uninstall dam_inventory
```

**Comment by hello-deepak** [comment]
Thank you @swainn . Problem solved.
