### ISSUE TITLE
Custom settings don't load if there is only one present in the app. 

### ISSUE THREAD

**Issue by rfun** [tethysplatform/tethys#576]
The issue is that if a Tethys application has only one custom setting in its app.py , you get the following error when starting your instance: 

ERROR:tethys.app_base:'CustomSetting' object is not iterable

Also, the setting is not shown in the administration page for that application. To replicate, 

1. Scaffold a tethys app
2. Add a custom setting to app.py
3. Install the app and start your portal

Here is a test app if you would like to replicate the issue faster on your system: https://github.com/rfun/failed-custom-setting

I would like to debug this but I won't have time until next week to do so and hence posting it here first to keep track as well as maybe someone else already has a fix for this.

**Comment by rileyhales** [comment]
I just discussed with Rohit but i'll post it here for the sake of advancing the conversation.

The be slightly more specific about what causes the problem, it seems to be that in a tethysapp class you can't return an instance of CustomSetting. That is, you cannot have this:
```
    def custom_settings(self):
        return CustomSetting(
            name='test_setting',
            type=CustomSetting.TYPE_STRING,
            description='test_setting',
            required=False
        )
```

You must have this:
```
    def custom_settings(self):
        return (CustomSetting(
            name='test_setting',
            type=CustomSetting.TYPE_STRING,
            description='test_setting',
            required=False
        ),  )
```

Looking at it from a non-tethys-user point of view, i feel like an app class function that wants you to specify custom settings should allow you to return a single instance of `CustomSetting` or a tuple/list of them.

**Comment by swainn** [comment]
So this is not a bug, but a case of user error. The API documentation is very clear that it expects a list or tuple of CustomSettings objects: http://docs.tethysplatform.org/en/stable/tethys_sdk/app_settings.html?highlight=custom%20settings#custom-settings

That said, I'd be willing to take a pull request on this as long as the pattern is updated for all app settings.

**Comment by rfun** [comment]
Definitely a User error. I am sorry but I think I jumped the gun on this one. Closing issue.
