### ISSUE TITLE
NGINX and uWSGI Support

### ISSUE THREAD

**Issue by swainn** [tethysplatform/tethys#60]
Investigate moving from apache with mod_wsgi to nginx with uwsgi.

**Comment by swainn** [comment]
See: https://www.youtube.com/channel/UCwwCdzSH0B-Ja3QQqBR3Q9A

**Comment by sdc50** [comment]
Add gen commands for adding templates for NGINX and uWSGI

**Comment by swainn** [comment]
@sdc50 fix this! Please.
