### ISSUE TITLE
Daphne updated to 3.0.0

### ISSUE THREAD

**Issue by rfun** [tethysplatform/tethys#611]
Recently, while uninstalling a package, my tethys virtual environment was updated (I know bad idea) and it started giving the error : 

```

ERROR:daphne.http_protocol:Traceback (most recent call last):
  File "/Users/rohitfun/miniconda3/envs/test_tethys/lib/python3.7/site-packages/daphne/http_protocol.py", line 180, in process
    "server": self.server_addr,
TypeError: __call__() got an unexpected keyword argument 'receive'

ERROR:django.channels.server:HTTP GET / 500 [0.00, 127.0.0.1:59011]
```

So I removed my main environment and tried to reinstall using the default command from Tethys Docs and it still showed the same error. I tried again in a fresh new environment with a different name and saw the same issue. After digging a bit deeper, it seems like daphne was updated to 3.0.0 a few days ago and that is the issue here. When we setup a new environment it is installing daphne v3 vs v2.5 which is installed in previous environments and considering that this is a major version change, it does seem to break things.  I don't know which package is pulling in Daphne, but it might be channels. 

However, if we force 2.5.0 to be installed ( conda install -c conda-forge daphne=2.5.0 ) it starts working again as expected. So if we just fix the version in the meta.yaml for tethys-platform package, it might be a good solution for now. 

Thoughts?

**Comment by swainn** [comment]
I've submitted PR #612 to pin Daphne to 2.5.X for our upcoming 3.2 release. However, I'm assigning this issue to the 3.3 milestone so that we can investigate if it is possible to upgrade Tethys to use Daphne 3.0.

**Comment by swainn** [comment]
#753 migrates Tethys to use Daphne 3 as well.
