### ISSUE TITLE
MFA Email Method Error

### ISSUE THREAD

**Issue by ezrajrice** [tethysplatform/tethys#621]
Using the new MFA with email as the secondary authentication method gives the following error:

```
Traceback (most recent call last):
  File "./django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "./django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "./django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "./mfa/Email.py", line 38, in start
    if sendEmail(request, request.user.username, request.session["email_secret"]):
  File "./mfa/Email.py", line 17, in sendEmail
    return send([user.email],"OTP", res.content.decode())
  File "./mfa/Common.py", line 8, in send
    From = "%s <%s>" % (settings.EMAIL_FROM, from_email_address)
  File "./django/conf/__init__.py", line 80, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'EMAIL_FROM'
```

I have a fully functioning email configuration that I have tested using the password recovery functionality. The portal_config.yml file doesn't have an EMAIL_FROM parameter in either the MFA_CONFIG or EMAIL_CONFIG sections from what I saw in the [documentation](http://docs.tethysplatform.org/en/stable/tethys_portal/configuration.html). Any clue on what setting needs to be added and where to make this method work?

**Comment by swainn** [comment]
Looks like this is a documentation problem. @ezrajrice have you tried setting an EMAIL_FROM setting? Here are two different configs I have that are working:

```yaml
  EMAIL_CONFIG:
    EMAIL_BACKEND: django.core.mail.backends.smtp.EmailBackend
    EMAIL_USE_TLS: True
    EMAIL_HOST: smtp.gmail.com
    EMAIL_PORT: 587
    EMAIL_HOST_USER: <email@gmail.com>
    EMAIL_HOST_PASSWORD: <gmail_password>
    EMAIL_FROM: 'Some Name'

  EMAIL_CONFIG:
    EMAIL_BACKEND: django.core.mail.backends.smtp.EmailBackend
    EMAIL_HOST: smtp.sendgrid.net
    EMAIL_PORT: 587
    EMAIL_HOST_USER: apikey
    EMAIL_HOST_PASSWORD: <send-grid-api-key>
    DEFAULT_FROM_EMAIL: <from@email.address>
    EMAIL_FROM: 'Some Name'
```

**Comment by ezrajrice** [comment]
I'm getting a new error.

```
Traceback (most recent call last):
  File "./django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "./django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "./django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "./mfa/Email.py", line 38, in start
    if sendEmail(request, request.user.username, request.session["email_secret"]):
  File "./mfa/Email.py", line 17, in sendEmail
    return send([user.email],"OTP", res.content.decode())
  File "./mfa/Common.py", line 11, in send
    return email.send(False)
  File "./django/core/mail/message.py", line 291, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "./django/core/mail/backends/smtp.py", line 110, in send_messages
    sent = self._send(message)
  File "./django/core/mail/backends/smtp.py", line 122, in _send
    from_email = sanitize_address(email_message.from_email, encoding)
  File "./django/core/mail/message.py", line 119, in sanitize_address
    address = Address(nm, addr_spec=addr)
  File "/home/ubuntu/miniconda3/envs/tethys3/lib/python3.7/email/headerregistry.py", line 42, in __init__
    a_s, rest = parser.get_addr_spec(addr_spec)
  File "/home/ubuntu/miniconda3/envs/tethys3/lib/python3.7/email/_header_value_parser.py", line 1624, in get_addr_spec
    token, value = get_local_part(value)
  File "/home/ubuntu/miniconda3/envs/tethys3/lib/python3.7/email/_header_value_parser.py", line 1434, in get_local_part
    if value[0] in CFWS_LEADER:
IndexError: string index out of range
```
My config looks like this:
```YAML
  EMAIL_CONFIG:
    EMAIL_BACKEND: 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST: 'localhost'
    EMAIL_PORT: 25
    EMAIL_HOST_USER: '<foo@bar.com>'
    EMAIL_HOST_PASSWORD: '<foo_bar>'
    EMAIL_USE_TLS: True
    DEFAULT_FROM_EMAIL: '<noreply@foo.bar>'
    EMAIL_FROM: 'Foo Bar'
```

**Comment by swainn** [comment]
@ezrajrice it looks like it is choking on the sanitize_address method when trying to send the email. I'm not sure exactly what that means, but seems to indicate something is wrong with the email address being used to send the email?

Another thought is, if you are using your own local Postfix email server, have you configured it to use TLS? b/c you still have the `EMAIL_USE_TLS: True` setting. Probably would cause problems if you haven't set up Postfix to do that for you.

**Comment by swainn** [comment]
As a side note are you trying to use your own Postfix email server? I'd recommend using a 3rd-party service like SendMail or you can set it up using your email provider. I tested this using SendMail and Gmail. I didn't try it with a local Postfix server. The advantage of using an email service is that they deal with all the regulations and making sure your email doesn't go to spam.

There is an example of setting up email using SendGrid in our documentation: http://docs.tethysplatform.org/en/stable/installation/production/configuration/advanced/email_config.html?highlight=email

That document also has the old instructions for setting up Postfix, they are out of date and I can't guarantee they work.

This is a good tutorial for setting up email in Django through a Gmail account:

https://medium.com/@_christopher/how-to-send-emails-with-python-django-through-google-smtp-server-for-free-22ea6ea0fb8e

I'm sure the process is similar if your company uses a different email provider.

**Comment by swainn** [comment]
Also: I found that the documentation for setting up email for Multi-Factor Authentication does mention the `EMAIL_FROM` setting, which is specific for setting up MFA I believe.

http://docs.tethysplatform.org/en/stable/installation/production/configuration/advanced/multi_factor_auth.html#email-configuration

**Comment by ezrajrice** [comment]
> 
> 
> @ezrajrice it looks like it is choking on the sanitize_address method when trying to send the email. I'm not sure exactly what that means, but seems to indicate something is wrong with the email address being used to send the email?
> 
> Another thought is, if you are using your own local Postfix email server, have you configured it to use TLS? b/c you still have the `EMAIL_USE_TLS: True` setting. Probably would cause problems if you haven't set up Postfix to do that for you.

I set up TLS with my Postfix configuration and have thoroughly tested it. There aren't any issues with my emails going into the spam folder or for sending emails to my inbox using the password recovery or the bug reporting in the apps. I'll keep playing with it to see what I can figure out. I may have to do as you suggest and switch to an email provider.



> 
> 
> Also: I found that the documentation for setting up email for Multi-Factor Authentication does mention the `EMAIL_FROM` setting, which is specific for setting up MFA I believe.
> 
> http://docs.tethysplatform.org/en/stable/installation/production/configuration/advanced/multi_factor_auth.html#email-configuration

I'm glad it's explained somewhere. I was just going directly to the portal_config.yml documentation. I did notice that in the example you linked, the boolean values are lowercase (i.e. true instead of True). Is that how they're supposed to be or does it not matter?

**Comment by swainn** [comment]
I don't think the case matters for True or False in yaml files. Not sure though. 

Looking over the tutorial for forgotten passwords, I noticed that the `DEFAULT_FROM_EMAIL` parameter is recommended to be set as follows: `"<Some Name some@email.com>"` (angle brackets are literal in this case).

However, for the MFA email config we recommend `DEFAULT_FROM_EMAIL` be set as follows: `"some@email.com"`.

Hopefully we didn't inadvertently make the MFA email and forgotten email configurations incompatible...

**Comment by ezrajrice** [comment]
I just tested this by removing the angle brackets and that fixed the issue. It seems that the angle brackets don't get dropped when MFA parses the email from the settings. I also tested the password recovery with this change and found that it still works without the angle brackets, although it has some quirks. 
You can't add a name though for the password recovery. Without MFA, you can send using a nickname when configured as `"Name <some@email.com>"` or as `"<Name some@email.com>"`. You can enable email MFA, but there are two things you have to do:
1. Remove angle brackets from `DEFAULT_FROM_EMAIL`
2. Remove nickname from `DEFAULT_FROM_EMAIL` 

   i.e. `DEFAULT_FROM_EMAIL: "<Name some@email.com>"` -> `DEFAULT_FROM_EMAIL: "some@email.com"`

**Comment by swainn** [comment]
Interesting. I think MFA gets its nickname from the extra parameter: `EMAIL_FROM`. Perhaps we could refactor Forget Password to do the same?

**Comment by ezrajrice** [comment]
That seems the most plausible to me. You have my vote for that change.

**Comment by ezrajrice** [comment]
This turned out to be easier than I thought it would be. I just created a subclass from Django's built-in `PasswordResetView` class and set the form's `email_from` parameter to the same method used in django-mfa2. I'm submitting a PR for this.
