### ISSUE TITLE
Custom Setting with Type UUID

### ISSUE THREAD

**Issue by msouff** [tethysplatform/tethys#623]
Tethys app custom settings support string, integer, float, and boolean. Right now we have to use TYPE_STRING for apps that require a unique identifier setting due to the lack of support for TYPE_UUID. This can can easily result in errors since in reality the these settings would not accept any string but a UUID.

Postgres does support UUID columns so it would be a matter of adding it as an extra option to the Tethys custom setting class (CustomSetting).

**Comment by swainn** [comment]
@msouff I should mention that all values for CustomSettings are stored as strings (regardless of type). They are automatically cast back to the correct type when you get the setting.
