### ISSUE TITLE
Cent OS Production Docs

### ISSUE THREAD

**Issue by swainn** [tethysplatform/tethys#64]
Add docs for CentOS deployment and EPEL:

Drew's notes:

Change the VM network configuration to “Bridged Adapter” (Oracle VirtualBox). So the VM and host are in the same subnet. 

Install Centos 6.6 x64. Some available options 

Desktop
Minimal Desktop
Minimal
Basic Server
Database Server
Web Server
Virtual Host
Software Development Workstation

Install ‘Desktop’ for development;
Install ‘Minimal’ for deployment; 
The following steps are referred to ‘Minimal’.

### Create a new user with root privilege
adduser mynewuser
passwd mynewuser
visudo
mynewuser ALL=(ALL) ALL
exit

### Activate Internet Connection
sudo su
vi /etc/sysconfig/network-scripts/ifcfg-eth0

DEVICE=eth0
HWADDR=Do Not Modify This!!!
NM_CONTROLLED=NO
ONBOOT=YES
BOOTPROTO=dhcp

service network restart

ifconfig eth0

###disable ipv6
vi /etc/sysctl.conf
net.ipv6.conf.all.disable_ipv6 = 1
(If the network card name is eno16777736)
net.ipv6.conf.eno16777736.disable_ipv6 = 1

reboot

#find the ip (it should be a ipv4 address as we already disable ipv6 service above)
ifconfig eth0 

SSH to the VM using that ip via a SSH client (eg. sshsecureshellclient-3.2.9 for Windows) so you can do Copy and Paste…

---------------------------

### Update system
su
yum update
reboot

### install epel-release-6-8.noarch.rpm
yum install wget
yum repolist
wget http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
rpm -ivh epel-release-6-8.noarch.rpm
yum repolist

yum install nano

### install python2.7 pip virtualenv and... without destroying existing python2.6 and YUM

https://www.digitalocean.com/community/tutorials/how-to-set-up-python-2-7-6-and-3-3-3-on-centos-6-4

yum groupinstall -y development
yum install -y zlib-dev openssl-devel sqlite-devel bzip2-devel
wget http://www.python.org/ftp/python/2.7.6/Python-2.7.6.tar.xz
yum install xz-libs
xz -d Python-2.7.6.tar.xz
tar -xvf Python-2.7.6.tar
cd Python-2.7.6
./configure --prefix=/usr/local  --enable-shared
make
make altinstall
export PATH="/usr/local/bin:$PATH"

###add /usr/local/lib to file /etc/ld.so.conf to expose python2.7 libraries
nano /etc/ld.so.conf
##add to end: 
/usr/local/lib 
ldconfig

which python2.7
python2.7 -V

cd ~
wget https://pypi.python.org/packages/source/s/setuptools/setuptools-1.4.2.tar.gz
#find the exact file name
tar -xvf setuptools-1.4.2.tar.gz
cd setuptools-1.4.2
python2.7 setup.py install
curl https://raw.githubusercontent.com/pypa/pip/master/contrib/get-pip.py | python2.7 -
pip -V
pip install virtualenv
which virtualenv

###install docker
yum install docker-io
service docker start
#test docker
docker ps
docker --version
#start docker when boot
chkconfig docker on
sudo usermod -aG docker XXX_username
sudo groupadd docker
sudo gpasswd -a ${USER} docker
reboot
#logout and login

#install python-devel
sudo su
yum install python-devel
yum install postgresql-devel
yum install libxml2-devel
yum install libxslt-devel
yum install git
exit 

--------------Update git on RHEL/CentOS 6 - 64bit (optional)-----------------
http://tecadmin.net/how-to-upgrade-git-version-1-7-10-on-centos-6/
sudo rpm -i 'http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm'
sudo rpm --import http://apt.sw.be/RPM-GPG-KEY.dag.txt
sudo nano /etc/yum.repos.d/rpmforge.repo
###change all enabled=0 flag to enabled=1 and save it.
sudo yum update git
git --version
sudo yum clean all
sudo nano /etc/yum.repos.d/rpmforge.repo
###change all enabled=1 flag to enabled=0 and save it.
sudo yum update ###should return no errors

-----install Tethys (development mode)-----------
Step 4 Create Virtual Environment and Install Tethys Platform

sudo mkdir -p /usr/lib/tethys
sudo chown `whoami` /usr/lib/tethys
virtualenv --no-site-packages /usr/lib/tethys
. /usr/lib/tethys/bin/activate
git clone https://github.com/CI-WATER/tethys /usr/lib/tethys/src
pip install --upgrade -r /usr/lib/tethys/src/requirements.txt
python /usr/lib/tethys/src/setup.py develop
deactivate
. /usr/lib/tethys/bin/activate

tethys docker init

###if got error like "from docker.client import DEFAULT_DOCKER_API_VERSION" in "/usr/lib/tethys/src/tethys_apps/cli/docker_commands.py"
sudo docker version
### find API VERSION like 1.17
nano /usr/lib/tethys/lib/python2.7/site-packages/docker/client.py
#add these lines
DEFAULT_DOCKER_API_VERSION = '1.17'
DEFAULT_TIMEOUT_SECONDS = 60
STREAM_HEADER_SIZE_BYTES = 8

tethys docker start

tethys gen settings -d /usr/lib/tethys/src/tethys_apps

#editing settings.py
nano /usr/lib/tethys/src/tethys_apps/settings.py

tethys manage syncdb

tethys manage start

----------Tethys Production Installation-----------------------

sudo su
yum install httpd-devel

chown -R apache:apache /usr/lib/tethys/src
mkdir -p /usr/local/pythonenv
/usr/local/bin/virtualenv --no-site-packages /usr/local/pythonenv/BASELINE

wget https://github.com/GrahamDumpleton/mod_wsgi/archive/3.5.tar.gz
tar xvfz 3.5.tar.gz
cd  mod_wsgi-3.5
./configure --with-python=/usr/local/pythonenv/BASELINE/bin/python
make
make install

#add this line to "/etc/httpd/conf/httpd.conf"
LoadModule wsgi_module modules/mod_wsgi.so

service httpd restart
httpd -M | grep wsgi

nano /etc/httpd/conf.d/tethys-default.conf

WSGISocketPrefix run/wsgi
WSGIPythonHome /usr/local/pythonenv/BASELINE
#WSGIPythonPath /usr/local/pythonenv/BASELINE/lib/python2.7:/usr/lib/ckan/default/lib/python2.7/site-packages
#WSGIPythonPath /usr/local/pythonenv/BASELINE/lib/python2.7

#WSGIPythonHome /usr/lib/ckan/default
WSGIPythonPath /usr/lib/tethys/lib/python2.7:/usr/lib/tethys/lib/python2.7/site-packages:/var/www/tethys/apps

<VirtualHost 0.0.0.0:80>
    ServerName 10.2.115.200 ****Change to your IP or domain
    ServerAlias 10.2.115.200 *****Change to your IP or domain
    Alias /static/ /var/www/tethys/static/
    <Directory /var/www/tethys/static/>
        #Require all granted
    </Directory>
    WSGIScriptAlias / /usr/lib/tethys/src/tethys_portal/wsgi.py
    <Directory /usr/lib/tethys/src/tethys_portal>
        <Files wsgi.py>
            #Require all granted
        </Files>
    </Directory>
    # Daemon config
    WSGIDaemonProcess tethys_default \
     python-path=/usr/lib/tethys/src/tethys_portal:/usr/lib/tethys/lib/python2.7/site-packages:/var/www/tethys/apps
    WSGIProcessGroup tethys_default
    #Logs
    ErrorLog /var/log/httpd/tethys_default.error.log
    CustomLog /var/log/httpd/tethys_default.custom.log combined
</VirtualHost>

mkdir -p /var/www/tethys/static
mkdir -p /var/www/tethys/apps
chown -R apache:apache /var/www/tethys

nano /usr/lib/tethys/src/tethys_apps/settings.py
DEBUG = False
TEMPLATE_DEBUG = False
ALLOWED_HOSTS = ['www.example.com','127.0.0.1'] ***to your IP or domain
STATIC_ROOT = '/var/www/tethys/static'

. /usr/lib/tethys/bin/activate
tethys syncstores all
cd /usr/lib/tethys/src
python manage.py collectstatic

sudo chown -R apache:apache /usr/lib/tethys
sudo chown -R apache:apache /var/www/tethys

mkdir -p /var/www/.tethyscluster
chown -R apache:apache /var/www/.tethyscluster

###add a rule in the firewall conf
###http://www.binarytides.com/open-http-port-iptables-centos/
###http://wiki.centos.org/HowTos/Network/IPTables
sudo service iptables stop
sudo iptables -I INPUT 5 -i eth0 -p tcp --dport 80 -m state --state NEW,ESTABLISHED -j ACCEPT
sudo service iptables save
sudo service iptables start
nano /etc/sysconfig/iptables

service httpd restart 

nano /var/log/httpd/tethys_default.error.log

-------------------END----------------------

**Comment by sdc50** [comment]
Drew ran into some problems involving the SELinux setting when  installing Tethys 1.2 on CentOS 6.7.  It apparently needs to be disabled for Tethys 1.2, whereas with 1.1 and before it didn't. Disabling it may expose some security issues. This needs to be researched more. See this forum discussion: https://groups.google.com/forum/#!topic/tethysplatform/rbZmC5i8zxs

Documentation should also be created for CentOS 7, where there seems to be a similar problem to issue 96: https://github.com/tethysplatform/tethys/issues/96.

**Comment by snowman2** [comment]
For SELinux, it may be best to avoid the docker all together. I just installed postgresql without docker and I am able to leave SELinux enabled.

See: https://wiki.postgresql.org/wiki/YUM_Installation

RHEL 7 Setup:
$ yum install postgresql-server postgis postgis-utils postgis-docs
$ postgresql-setup initdb
$ systemctl enable postgresql
$ systemctl start postgresql

Troubleshooting:
If you see:

django.db.utils.OperationalError: FATAL:  Ident authentication failed for user "tethys_default"

http://www.cyberciti.biz/faq/psql-fatal-ident-authentication-failed-for-user/

vim /var/lib/pgsql/data/pg_hba.conf
local	all	all	trust 
host	all	127.0.0.1/32	trust
$ systemctl restart postgresql


Create Database and Database Users
-------------------------------------

Create three database users with databases. You will be prompted to create passwords for each user. Take note of the passwords, because you will need to use them in the next step. To do so, run the following commands in the terminal:

    sudo -u postgres createuser -S -D -R -P tethys_default
    sudo -u postgres createdb -O tethys_default tethys_default -E utf-8

    sudo -u postgres createuser -S -d -R -P tethys_db_manager
    sudo -u postgres createdb -O tethys_db_manager tethys_db_manager -E utf-8

    sudo -u postgres createuser --superuser -d -R -P tethys_super
    sudo -u postgres createdb -O tethys_super tethys_super -E utf-8

**Comment by sdc50** [comment]
This issue will be addressed by issue #146
