### ISSUE TITLE
Cannot Sync Workspace Changes in Production

### ISSUE THREAD

**Issue by swainn** [tethysplatform/tethys#645]
Discussion #636 revealed an issue with the `collectworkspaces` functionality. There is no way to "sync" new files introduced into the workspaces through development to an already "collected" workspace. 

It's more complicated than this, but the current behavior essentially boils down to two options:

1. Ignore new files (default behavior).
2. Overwrite with only the new files (with the `--force` option).

If any files were added to the collected workspace during usage of the app, these would be overwritten and lost when using `tethys manage collectworkspaces --force` during an app update. On the other hand, your new files wouldn't be copied to the collected workspace if you didn't use `--force`.

**Comment by swainn** [comment]
One way to resolve this would to remove the symlink entirely and refactor collect workspaces to work like collect static and do a one-way sync to the workspaces directory. We may also need to update the get_workspaces commands to use the workspaces setting when not in debug (i.e. in production mode) to get the location of the workspace root directory and derive the full path.

**Comment by swainn** [comment]
We would also need to have some sort of migration path:
* Check for link and remove it and copy files back to app source if present?

**Comment by sdc50** [comment]
I propose that we create a new "workspace" called `app_resouces`. It would not be collected like other workspaces, but would be tracked.

**Comment by swainn** [comment]
The new Paths API sidesteps this concern.
