### ISSUE TITLE
Overwriting an app's name through Site Admin causes app to load with 500 error

### ISSUE THREAD

**Issue by shawncrawley** [tethysplatform/tethys#653]
Using Tethys Platform 3.1.1,  I tried to edit my application's name using the Site Admin tools (see following screenshot), and after doing so I ended up getting a 500 error when loading the application.

![image](https://user-images.githubusercontent.com/12499203/107678890-8ee60980-6c61-11eb-93ff-ab445f3c4f6e.png)

Here is the error from the tethys log:

```bash
2021-02-11 17:58:01,733 ERROR    Internal Server Error: /apps/wpod-dashboard/
Traceback (most recent call last):
  File "./django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "./django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "./django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./tethys_apps/base/workspace.py", line 422, in wrapper
    the_workspace = _get_app_workspace(app)
  File "./tethys_apps/base/workspace.py", line 360, in _get_app_workspace
    project_directory = os.path.dirname(sys.modules[app_class.__module__].__file__)
AttributeError: 'NoneType' object has no attribute '__module__
```
This only breaks the app's specific pages from loading, not the Tethys Portal itself. If I change the name back to what it was originally through the Site Admin tools, I no longer get the error and things work as expected.

**Comment by swainn** [comment]
@shawncrawley thank you for reporting. It appears from the stack trace that there may be an issue in the way the workspace is being derived. I'll take a look and try to reproduce on my end.

**Comment by swainn** [comment]
@shawncrawley I have confirmed that this is an issue. The `app_workspace` decorator uses the function `get_app_class()` to get the app class. The `get_app_class()` function gets the app class (from app.py) given an app model and guess what it uses to match them? Yup. The name:

```
141      def get_app_class(app):
142  	    apps_s = SingletonHarvester().apps
143  	    for app_s in apps_s:
144  ->	        if app_s.name == app.name:
145  	            return app_s
```

See: tethys_apps/utilities.py line 144

The better way to do this would be to use the package_name, which is treated as an ID and not editable (or exposed) in app settings.

**Comment by shawncrawley** [comment]
@swainn Glad I'm not crazy - that makes sense. Thanks for looking into that.
