### ISSUE TITLE
psychopg2 2.9 breaks Tethys in dev

### ISSUE THREAD

**Issue by swainn** [tethysplatform/tethys#698]
The Development version of Tethys will not start because of an error caused by a new version of psychopg2. See: https://stackoverflow.com/questions/68024060/assertionerror-database-connection-isnt-set-to-utc

Pin to 2.8.9?

**Comment by swainn** [comment]
This issue was reported to Django here:

https://code.djangoproject.com/ticket/32856

And an MR to fix it was reported here:

https://code.djangoproject.com/ticket/32856

However, since 2.2 is LTS version, they don't want to make the change. Doesn't appear to be a problem for Django 3.x. So the recommendation is to pin psycopg2 < 2.9 if you pin to Django 2.2

**Comment by msouff** [comment]
Thanks for looking into this.

**Comment by swainn** [comment]
Fixed in #699
