### ISSUE TITLE
Update the OpenLayers templated CDN endpoint

### ISSUE THREAD

**Issue by shawncrawley** [tethysplatform/tethys#710]
Per the official Tethys Platform documentation on the MapView gizmo, "If you need a specific version of OpenLayers you can specify the version number using the ol_version class attribute on the MapView class:"
```python
MapView.ol_version = '4.6.5' 
```

I tried to use version 6.6.1, but my application failed upon load due to not being able to find the associated CSS and JS. It turns out that https://www.jsdelivr.com/package/npm/openlayers is now deprecated. The official suite of CDN libraries is now https://www.jsdelivr.com/package/npm/ol.

It seems that to fix this, [this line](https://github.com/tethysplatform/tethys/blob/b41ca3baf8338c406f8ce3f9fa53ab8a862641e0/tethys_gizmos/gizmo_options/map_view.py#L316) would need to be updated accordingly. Per the [official OpenLayers download page](https://openlayers.org/download/), these are the link/script CDN connections they show:
```html
<script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.6.1/build/ol.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.6.1/css/ol.css">
```

**Comment by swainn** [comment]
Thanks for the heads up. Think you could work this into a pull request?

**Comment by shawncrawley** [comment]
Yep. I'll get it submitted soon.
