### ISSUE TITLE
Add CITATION.cff

### ISSUE THREAD

**Issue by swainn** [tethysplatform/tethys#716]
GitHub now supports CITATION.cff files to let people know how to cite your software. We should add one of these to Tethys Platform. For more details, see:

* https://github.blog/2021-08-19-enhanced-support-citations-github/
* https://citation-file-format.github.io/

**Comment by danames** [comment]
Nice new feature! Yes good idea to add it to Tethys repo...
**********************************************************************
Daniel P. Ames, Ph.D., P.E.
Professor, Civil & Environmental Engineering,Brigham Young University,
Provo, Utah, USA
Past-President, International Environmental Modelling & Software Society
Editor-in-Chief, Environmental Modelling & Software
<http://ceen.et.byu.edu/content/dan-ames>
https://ceen.byu.edu/directory/dan-p-ames
http://www.researchgate.net/profile/Daniel_Ames
http://scholar.google.com/citations?user=S0GUCeUAAAAJ

**********************************************************************
