### ISSUE TITLE
Error to bind the THREDDS data directory 

### ISSUE THREAD

**Issue by Benminoungou** [tethysplatform/tethys#718]
I'm trying to install the THREDDS Data Server (TDS) using the Docker image developed by Unidata on windows 10. 

When I use the command tethys docker init -c thredds and press enter to accept the defaults shown in square brackets, the terminal is still asking me to provide a valid directory to to bind the THREDDS data directory. Below is the error I got:

OSError (22, 'The syntax of the file, directory, or volume name is incorrect')

I think this is a bug that needs to be fixed in windows. Below is a screenshot of my terminal:
![image](https://user-images.githubusercontent.com/14221110/130283520-2b57ce99-c649-48a3-8cf4-f8611f5e0241.png)

**Comment by swainn** [comment]
Hi, @Benminoungou thanks for posting this. Unfortunately, Windows support for Tethys Platform is experimental currently. I've never tested the Tethys Docker API w/ Docker for Windows. I'm curious, does it work when you supply a path?

**Comment by Benminoungou** [comment]
Dear @swainn thanks you for your response. It doesn't work when I supply a path. The problem persists. I would like to transfer to Linux. What do you think is the most stable Linux system for Tethys?
Best regards,
/Bernard

**Comment by ezrajrice** [comment]
@Benminoungou I've used Ubuntu for my Linux system for years and have found it to be a stable option for Tethys.
The current stable branch indicates the production installation instructions to be for Ubuntu 20.04 and CentOS 8 server. See [Tethys Platform Documentation -- Production Installation](http://docs.tethysplatform.org/en/stable/installation/production/overview.html#operating-system)

**Comment by ezrajrice** [comment]
Also my cursory review of your error shows the path to be incorrect. Windows paths use backslash "\\" whereas Linux paths use forward slash "/".  Your path error that results in "Please provide a valid directory" is caused by the path mixing these two methods. 

See "/C:\Users\minou/.tethys\thredds"

I suspect this is because at least part of the path aggregation is hard coded with forward slashes "/".

**Comment by swainn** [comment]
> I suspect this is because at least part of the path aggregation is hard coded with forward slashes "/".

Yeah, that path is the default provided by Tethys. I've labeled this as a bug.

**Comment by swainn** [comment]
> Regarding another aspect, I tried to create a python class but I get the following error:
> RuntimeError: Model class tethysapp.sirba_forecast.model.accessCode doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
> As suggested in the documentation, I tried adding the name of the application in the "portal_config.yml" file but the problem persists. The contents of the file are shown below:
> 
> version: 1.0
> name:
> apps: {}
> settings:
> SECRET_KEY: xxxx
> INSTALLED_APPS: [
> 'tethysapp.sirba_forecast',
> 'django.contrib.sites',
> 'sirba_forecast',
> 'apps/sirba-forecast/sirba_forecast',
> 'sirba-forecast/sirba_forecast']
> site_content: {}
> 
> I did some research and found that many encountered this issue in Django but none of the suggested solutions worked to fix the problem. Your help will be invaluable to me.

@Benminoungou could you post this as a separate issue/discussion?

**Comment by swainn** [comment]
@Benminoungou I'm happy to report that this will be fixed in Tethys 4, which should be released soon.
