### ISSUE TITLE
Jobs Table on the Gizmo Showcase is broken

### ISSUE THREAD

**Issue by sdc50** [tethysplatform/tethys#723]
When the jobs table on the Gizmo Showcase is rendered none of the Ajax calls are successful (all receive a 403 Forbidden error). 

I believe this is a result of #662. Since the code to handle secure Ajax calls is now embedded in the `app_base.js` it is only accessible from apps (and thus not the Gizmo Showcase). 

This is easily fixed by copying the JS code into the `gizmo_showcase/jobs_table.html`, but I'm wondering if we should consider another solution.

1. Should we make the Gizmo Showcase a special kind of app? I don't know if there are other similar issues where gizmos will work differently in an app versus outside an app, but since we use the showcase to test the gizmos, it may be a good idea to test them in an environment that is more similar to how they will actually be used.
2. Should we make the Ajax JS script more of a modular piece that can be imported easily in multiple settings (e.g. the app_base or the gizmo showcase)? This is a pattern that could/should be expanded on and is perhaps already being used in ATCore.

**Comment by swainn** [comment]
@sdc50 this is an interesting conundrum. I like the idea of turning the Gizmo showcase into an app. I also like the idea of creating modular JavaScript that can be included as needed. I have several scripts that I've included in a tethys_sdk as part of the map_layout_view branch. Regarding a gizmo showcase app I see a few options:

1. Create a normal app that is either pre-installed or is an optional install (perhaps via conda?).
2. Create a normal app that is pre-installed, but has settings set to not display it in the Apps Library. Then link to it from the Developers page.
3. Create a Tethys Extension (which doesn't show up in the Apps Library, but can have controllers and even UrlMaps.

With any of these options, I think we should have the app fully tested (ideally with GUI tests) and integrated into our test suite.

**Comment by sdc50** [comment]
@swainn all good ideas. My initial reaction is the option 3 would be the easiest way to keep the same functionality that we have now. But I'm wondering if we really do want the Gizmo Showcase to always be installed or if it should be optional (i.e. option 1). Maybe it should be installed as an extension by default, but then it could be uninstalled.

**Comment by swainn** [comment]
@sdc50 I like the idea of being able to run Tethys without it. It would provide a slightly lighter footprint for production instances. Perhaps we could move it to an extension in a minor release and then have the extension become an optional install in v4

**Comment by swainn** [comment]
Fixed by #742
