### ISSUE TITLE
tethys db migrate openssl error after 3.0.0 update 

### ISSUE THREAD

**Issue by msouff** [tethysplatform/tethys#761]
When trying to run tethys db migrate I get the following error

> undefined symbol: EC_POINT_get_affine_coordinates_GF2m, version OPENSSL_1_1_0

The error is coming from the cryptography package dependency. A quick google search revealed that this started happening when the openssl dependency for this package got updated to version 3.0.0 on conda-forge (see pyca/cryptography/issues/6712 and conda/conda/issues/11111)

Conda seems to be working on it so I'm not sure we need to do anything just yet. In the meantime, the solution to this error is:

`conda install "openssl<3.0.0" -c conda-forge`

**Comment by swainn** [comment]
@msouff unpinned openssl in PR #797. Linux tests passed, but Mac tests still failed with the openssl error.

**Comment by swainn** [comment]
Unpinned in #927 and tests are passing on Mac and Linux.
