### ISSUE TITLE
Update Tethys Compute Docs

### ISSUE THREAD

**Issue by swainn** [tethysplatform/tethys#77]
Scott: 

I updated the Tethys Portal documentation and I decided to add blurbs about how the admin pages of Tethys Portal allow you to configure the different services and manage computing resources. Could you please review the latter? You'll find it here:

http://tethys-platform.readthedocs.org/en/dev/tethys_portal.html#manage-computing-resources

Also, we'll need updated documentation in the SDK docs to include descriptions of the job manager and other things that you've added for this release.

Also, can you add some blurbs about the new Job Manager capabilities in version 1.1.0 here:

http://docs.tethys.ci-water.org/en/dev/whats_new.html#job-manager

Also, any other changes you would like to summarize on this page

**Comment by sdc50** [comment]
This issue is now obsolete.
