### ISSUE TITLE
Need Updated App Migration Documentation for Tethys 4

### ISSUE THREAD

**Issue by swainn** [tethysplatform/tethys#776]
Tethys 4.0 will be making several breaking changes to how apps are developed. We need to write an app migration guide for Tethys 3 to 4 similar to what we wrote the Tethys 2 to 3 transition. This issue lists the various changes that will need to be dealt with:

Theme and Styles
- [x] Migrate glyphicons to [Boostrap icons](https://icons.getbootstrap.com/)

App Navigation

- [x] Add `nav-item` class to `li` elements in nav
- [x] Add `nav-link` class to `a` elements in nav
- [x] Move `active` class from `li` to `a`

Modals

- [x] Add `bs` names space to all bootstrap data attributes (e.g.: `data-xyz` -> `data-bs-xyz`)
- [x] `data-dismiss` -> `data-bs-dismiss`
- [x] `data-toggle` -> `data-bs-toggle`
- [x] `data-target` -> `data-bs-target`
- [x] Change `close` class on the close button to `btn-close` and remove the `&times`
- [x] Reorder the title and button elements in the modal header (title first, button second)

Buttons

- [x] `btn-default` -> `btn-secondary`

Tooltips

- [x] Add `bs` names space to all bootstrap data attributes (e.g.: `data-xyz` -> `data-bs-xyz`).

Gizmos

- [x] If specifying custom classes that are bootstrap data classes, add the `bs` namespace (e.g.: `data-xyz` -> `data-bs-xyz`).
- [x] If specifying glyphicons for buttons, update to use [Boostrap icons](https://icons.getbootstrap.com/)

Controllers, Consumers, and Handlers

- [x] Migrate to using `controller` decorator and remove the `url_maps` method from the app class in `app.py`
- [x] Use the `app_workspace` and `user_workspace` kwargs of the `controller` decorator to obtain the workspace objects
- [x] Use the arguments for the `controller` decorator to implement `login_required`, `permissions_required`, `ensure_oauth2`, and `enforce_quotas` instead of the separate decorators.
- [x] Use `consumer` decorator to register consumer endpoints 
- [x] User `handler` decorator to register Bokeh handlers
- [x] Use the `template` or `app_package` arguments in the `handler` decorator rather than having a separate controller function (in simple cases).
- [x] Use the `controller` argument in the `handler` decorator to connect a controller to a handler if additional logic is needed in the controller. Note: the controller for a handler should **not** be decorated with the `controller` decorator.
- [x] Replace `with_workspaces` and `with_request` decorators on handler functions with the corresponding arguments in the `handler` decorator.

Schedulers

- [x] Define scheduler app settings using the `schedulers` method in the app class.
- [x] Use the `get_scheduler()` app class method to get schedulers.

**Comment by swainn** [comment]
@sdc50 can you add to this list regarding breaking changes to the `jobs_table` gizmo?

**Comment by sdc50** [comment]
> can you add to this list regarding breaking changes to the `jobs_table` gizmo?

I don't think there are any breaking changes, but I'll double check when I update that PR.
