### ISSUE TITLE
Hide app info icon until hover

### ISSUE THREAD

**Issue by sdc50** [tethysplatform/tethys#778]
I feel like the new app info icon detracts from the app icon, and I propose hiding it until the user hovers over the app card.

![app_icon_info](https://user-images.githubusercontent.com/6454472/156611953-1f2905cc-6e13-48a3-b2c4-7d35f876961c.gif)

I know one concern with having hover events is how it works on a mobile device. I'm not sure how the best way to handle that on mobile would be, but am interested to hear ideas from others to do more mobile specific development.

**Comment by ezrajrice** [comment]
I've seen apps that treat hover items as double taps on mobile. It seemed
to work well whenever I used it, but it isn't intuitive so I don't know how
to indicate that at a glance.

Ezra Rice

**Comment by swainn** [comment]
@sdc50 I'd be fine with it being hidden until hover. I'm not sure that we need to do anything to enable the hover double-tap functionality that @ezrajrice mentioned. I think a lot of mobile browsers automatically do that for hover rules, but it would be good to test it first.

Another option would be to use a media query to only apply the hover effect when not on a mobile device.
