### ISSUE TITLE
Changing the `root_url` attribute of an app breaks the index URL

### ISSUE THREAD

**Issue by sdc50** [tethysplatform/tethys#779]
If I wanted to change the `root_url` from the value that the scaffold generates it would break the home view of the app. 

For example, if I change the `BokehTutorial` app's `root_url` to `'bokeh-demo'` :

```python
class BokehTutorial(TethysAppBase):
    """
    Tethys app class for Bokeh Tutorial.
    """

    name = 'Bokeh Tutorial'
    index = 'bokeh_tutorial:home'
    root_url = 'bokeh-demo'
```
I would get this error:

![image](https://user-images.githubusercontent.com/6454472/156620806-6161f3d6-25bd-4c07-ae4b-9e5e592b4226.png)

This is because  Tethys uses the `root_url` attribute to derive the URL namespace that is actually used to register the URLs. So for this to work we would need to also change the `index` attribute to:

```python
index = 'bokeh_demo:home`
```

This doesn't seem intuitive, so I propose that we deprecate defining the `index` attribute with the URL namespace and have Tethys add it in with the namespace that it is actually going to use to register the URLs.

As part of deprecating the current way the `index` attribute is defined we could provide backwards compatibility for one release cycle and print a deprecation warning similar to this:

![image](https://user-images.githubusercontent.com/6454472/156619557-82854a4e-cc17-4ee4-9860-0622d457f3a8.png)

**Comment by swainn** [comment]
> This doesn't seem intuitive, so I propose that we deprecate defining the index attribute with the URL namespace and have Tethys add it in with the namespace that it is actually going to use to register the URLs.

@sdc50 I approve of deprecating the url namespace part of the index attribute. Seems like a simple way to get around it.

> However, if we change the `index` to not include the namespace, then I think that frees up the `root_url` and it's not as important that it was originally defined from the `package`, so I think we can leave it as a simple string.

Leaving the root_url as a simple string will be better for our users I think.
