### ISSUE TITLE
Jobs Table doesn't allow for results url without monitor url

### ISSUE THREAD

**Issue by har96** [tethysplatform/tethys#786]
https://github.com/tethysplatform/tethys/blob/6e8b29597aa448acb169d861712a030e0eab7fc0/tethys_gizmos/gizmo_options/jobs_table.py#L153

Should be `and results_url` on this line. If `results_url` is specified but `monitor_url` is not, then the Results action will not show up.

**Comment by swainn** [comment]
Will be fixed by #821

**Comment by swainn** [comment]
Latest dev package of Tethys (which is Tethys 4) should include the fix for this.
