### ISSUE TITLE
Test and Update Production Installation Documentation

### ISSUE THREAD

**Issue by swainn** [tethysplatform/tethys#818]
- [x] Complete a production installation using manual instructions
- [x] Review all optional configuration documentation
- [ ] Complete the Docker production deployment tutorial

**Comment by speleophysics** [comment]
Just a note that the current Dockerfile tutorial is broken for 4.0.0-rc.8. It seems there was a change in the env name and paths since the dockerfile example was written. I think that 
`${CONDA_HOME}/bin/activate tethys`
should become
`${CONDA_HOME}/envs/tethys/bin/activate base`
in the app install commands.

**Comment by speleophysics** [comment]
The Salt scripts for the tutorial also need similar modification. This has gotten the example running with docker compose, though most of the example apps seem to have substantial problems with 4.0.

**Comment by swainn** [comment]
Hi @speleophysics thank you for bringing this to our attention. I thought I had reviewed the Docker tutorial, but it looks like it needs some work.

**Comment by swainn** [comment]
Thank you for bringing this to our attention. We'll make sure it gets updated.

**Comment by swainn** [comment]
@speleophysics I want to give you an update to let you know I haven't forgotten about this issue. 

> Just a note that the current Dockerfile tutorial is broken for 4.0.0-rc.8

Tethys 4 has been released, but the Docker tutorial still needs updating. I will update it after I finish resolving issues with the tutorial apps (see below).

> ...most of the example apps seem to have substantial problems with 4.0.

Prior to the Tethys 4 release, the Tethys 4 solutions for the tutorials had not been merged into the main branches or tagged. This has been done now so most of the apps should work.

However, I discovered that the Earth Engine tutorial solutions for Tethys 4 had not been completed. I've updated 2 of the 3 parts of the tutorial (though, the updates have not been released yet).

**Comment by swainn** [comment]
Hey @speleophysics, I have a PR up to fix this (#913). Take a look at this build of the docs for the PR: 

https://tethys-platform--913.org.readthedocs.build/en/913/installation/production/docker.html

Note: there is still an issue with the THREDDS app, so it shouldn't work. But all the other apps will.

**Comment by swainn** [comment]
PR #913 addresses this and has been merged. These changes will appear in the stable documentation with the release of 4.1, but are currently available on the [latest version of the docs](http://docs.tethysplatform.org/en/latest/installation/production/docker.html).
