### ISSUE TITLE
Django Session Security and ResourceQuota Warnings

### ISSUE THREAD

**Issue by swainn** [tethysplatform/tethys#823]
A developer at Aquaveo has been working on upgrading some of BYU's apps to Tethys 4 and encountered these warnings in the geoglows_hydroviewer app:

![image (1)](https://user-images.githubusercontent.com/5123221/170742154-6ba07be8-0200-44ac-8790-797c4e721570.png)

The session security warnings may be related to the fact that he didn't have a `portal_config.yml` setup (the `SECRET_KEY` gets generated every reload when that happens; see: https://stackoverflow.com/questions/38970832/session-data-corrupted-in-django). However, they didn't go away after we created the `portal_config.yml` even with a hard refresh.

Unclear what is causing the ResourceQuota warnings

**Comment by sdc50** [comment]
Currently if you use one of the workspace decorators and haven't configured workspace quotas then you'll get those warnings. #839 makes some changes to reduce the logging level and frequency of those warnings.

**Comment by swainn** [comment]
Improved with #839 

Create portal_config.yml to avoid the Suspicious Session warnings.
