### ISSUE TITLE
ModuleNotFoundError: No module named 'geopandas

### ISSUE THREAD

**Issue by john3641** [tethysplatform/tethys#826]
Hello,

In the utils.py file of a tethys app I am developing I have this statement:

import geopandas as gpd

But, on my develpment server, when I use tethys manage start,  keep getting this error:

ModuleNotFoundError: No module named 'geopandas'

but another app I have that does not include the import geopandas statement loads fine, even while I get the error for the one with the statement.  

I am using Ubuntu 20.04, on my desktop.  I installed Tethys 3.3 last summer, but a few days ago used the link provided by the Tethys platform website to upgrade (to 3.4).  

I figured I needed to install geopandas.  So from the (base) environment, I used

conda install geopandas

It installed smoothly.

But I still got the same error.

I guessed that maybe I should install from the (tethys) environment, so I did.  Many, many conflicts were listed, but geopandas 2.31 was eventually installed.

But even then I still got the same error when attempting to load the app using tethys manage start.

Your help would be much appreciated.

**Comment by swainn** [comment]
Sorry you are having difficulty with this @john3641. What's odd is that installing the package in the `tethys` environment is the correct solution. Did you install geopandas from the `conda-forge` channel like so:

```
conda install -c conda-forge geopandas
```
Can you provide the following?

1. Full error
2. Results of `conda list`
3. Results of `conda info`

**Comment by john3641** [comment]
Thanks so much @swainn .  I had used "conda install geopandas".  But just now, I used the line you show, "conda install -c conda-forge geopandas", and it apparently worked.  I'm not longer getting that ModuleNotFoundError.  Thanks so much for your help.  

I regret not trying "conda list" and "conda info" before using the line you gave me, just so you could know what happened.  However, I have the impression that I never really installed geopandas because, just before I tried the line you gave me, I figured it might be good to "conda uninstall geopandas", and this is how it went:

(tethys) john@johnVB:~$ conda uninstall geopandas
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are missing from the target environment:
  - geopandas

Sorry I didn't remember/think of checking by using "conda list" first, which now shows geopandas in the list of packages installed.

Thanks again!

**Comment by swainn** [comment]
👍
