### ISSUE TITLE
ensure_oauth2 decorator doesn't ensure a valid token

### ISSUE THREAD

**Issue by sdc50** [tethysplatform/tethys#831]
The `ensure_oauth2` decorator only ensures that the user has a particular provider connected to their account. I think the intent is that it actually ensures that the user is authenticated with that provider (or in other words, has a valid token). 

Currently it's possible to authenticate with a password, or a different provider, and then access a page that requires a particular provider. This will often lead to an error because the user does not have a valid access token from that provider.

**Comment by swainn** [comment]
Fixed by #839
