### ISSUE TITLE
Controller Decorator Docstring Not Rendering in Docs

### ISSUE THREAD

**Issue by swainn** [tethysplatform/tethys#847]
![image](https://user-images.githubusercontent.com/5123221/180574034-f3e274b1-cf8a-4917-853d-85d23cdc1784.png)

See: http://docs.tethysplatform.org/en/latest/tethys_sdk/routing.html

**Comment by swainn** [comment]
I wonder if it's related to these warnings in the latest build:

![image](https://user-images.githubusercontent.com/5123221/180574307-c09631e7-655f-4a78-b5e0-b969e22ef0b0.png)

https://readthedocs.org/projects/tethys-platform/builds/17513070/

**Comment by sdc50** [comment]
It looks like we just need to mock `social_django.utils`. I'm not sure why this just popped up now.
