### ISSUE TITLE
Tethys on windows WSL Ubuntu: fido2 Error

### ISSUE THREAD

**Issue by hello-deepak** [tethysplatform/tethys#868]
I installed the tethys in windows WSL ubuntu 18.04 using 
```
conda create -n tethys -c tethysplatform -c conda-forge tethys-platform

```
It went very well.

But when I tried to  configure db

```
tethys db configure

```

I got the following error:

![image](https://user-images.githubusercontent.com/7577697/187831654-c0443f97-9211-416e-8c7e-4182258f2a14.png)

Basically it  says the fido2 is not installed.

**Comment by hello-deepak** [comment]
The solution for this problem is to install 0.9.2 version to fido2.

```
pip install fido2==0.9.2
```
Make sure you delete the psql folder inside home/.tethys and again configure your db.

**Comment by msouff** [comment]
@hello-deepak Thanks for posting and figuring out a workaround.

@swainn since this comes from our mfa dependency, I went to their repo issues and I found that they recently updated fido2 from 0.9.1 to 1.0.0 via dependabot (https://github.com/mkalioby/django-mfa2/pull/61).
