### ISSUE TITLE
.env file is not copying inner content

### ISSUE THREAD

**Issue by suman111sanjel** [tethysplatform/tethys#895]
Hi Nathan and Team,

.env is the file where is store my credentials. when is installed tethys app, it is not copying the .env file. 
This is the error facing.
What could be the solution to this issue?
Tethys version in 3.4.4

Thank You
Suman

**Comment by swainn** [comment]
Hi @suman111sanjel, where are you storing the .env file in your app?

**Comment by suman111sanjel** [comment]
.env file is just alongside app.py inside tethys application.
![image](https://user-images.githubusercontent.com/35019841/207768429-09b6abcd-3149-4f42-9abf-a4dfb475b50e.png)

**Comment by swainn** [comment]
Try storing the .env file in the app workspace (see: https://docs.tethysplatform.org/en/stable/tethys_sdk/workspaces.html)

**Comment by suman111sanjel** [comment]
Thank You Nathan!
