### ISSUE TITLE
Add "access_app" permission to Proxy Apps

### ISSUE THREAD

**Issue by sdc50** [tethysplatform/tethys#935]
Currently the "access_app" permission that allows the visibility of apps to be controlled (if the `ENABLE_RESTRICTED_APP_ACCESS` setting is `True`) only applies to `TethysApp` instances, and not to `ProxyApp`s.

I would like the ability to assign the `access_app` permission to `Groups` for both types of app:

![image](https://user-images.githubusercontent.com/6454472/227596680-a09e61d9-3e22-4e13-bab5-4ee4929a36b4.png)

**Comment by sdc50** [comment]
I'm adding a bug to this issue, because they are related. The JavaScript that handles hiding and showing specific app permissions is using the app name and trying to derive the app package. The display name and the package don't always correspond. We either need to use the app package in the selector rather than the name, or somehow embed the app package as a data field.

**Comment by swainn** [comment]
Merged in #936
