### ISSUE TITLE
[BUG] Windows conda package doesn't include any non-python files

### ISSUE THREAD

**Issue by sdc50** [tethysplatform/tethys#937]
I was helping someone install Tethys on Windows and it appears that that the scaffold templates and the html template files are missing. I'm assuming it doesn't include any of the non-python files.

**Comment by sdc50** [comment]
It looks like it was for tethys 3.4.3

**Comment by swainn** [comment]
@sdc50 I wonder if they installed the package that is on conda-forge. I seem to recall that we were having issues with the data files on that.

**Comment by swainn** [comment]
There is now a valid package for 4.1 on conda-forge, which should resolve any issues with channel order. We'll be dropping the tethysplatform channel in favor the the conda-forge channel.
