### ISSUE TITLE
Style difference between Proxy and Installed apps 

### ISSUE THREAD

**Issue by romer8** [tethysplatform/tethys#951]
### Problem
In the apps page in the library, there is no immediate way to tell which app is a proxy app and which one is an installed app.
### Current Solution
Currently, the only way to distinguish between them is to add a custom template for it. 
### Proposed

**Solution 1**:
Add a background image to the card indicating that is a proxy app or an installed app. The following image shows a little arrow that indicates proxy app
![image](https://github.com/tethysplatform/tethys/assets/43544549/ae289fc1-bab3-46e6-a9a6-46ac13f46aea)

**Solution 2** :
Add proxy apps and installed apps in different rows with a title indicating proxy/installed apps

**Comment by swainn** [comment]
This feature should be configurable and off by default.

**Comment by swainn** [comment]
Addressed by #989
