### ISSUE TITLE
Invalid Links for Map View Controls

### ISSUE THREAD

**Issue by Jason-mcm** [tethysplatform/tethys#976]
The links for the Map View Controls sections are invalid and returning a 404 error. This includes the links for the Fullscreen, MousePosition, Rotate, ScaleLine, ZoomSlider, and ZoomToExtent.

![image](https://github.com/tethysplatform/tethys/assets/86077146/326245fa-1844-46e1-8d17-664bbe43e6c9)

Workaround: 
The documentation for these controls can be found at https://openlayers.org/en/latest/apidoc/

Steps: 
1. Navigate to https://docs.tethysplatform.org/en/stable/tethys_sdk/gizmos/map_view.html#tethys_sdk.gizmos.MVDraw
2. Scroll down to the Controls section
3. Click one of the links

**Comment by swainn** [comment]
@Jason-mcm thanks for reporting. You can view the OpenLayers documentation about these controls here: https://openlayers.org/en/v6.15.1/apidoc/module-ol_control_Control-Control.html 

See the Subclasses section.
