### ISSUE TITLE
tethys db command not working

### ISSUE THREAD

**Issue by kfh01** [tethysplatform/tethys#981]
tethys db configure, init, and start all not working. 
Here's an example of what happens when I try to use db configure:
![image](https://github.com/tethysplatform/tethys/assets/143536954/aaeef46e-9b16-4efa-bc85-fa64e5b1cccb)

**Comment by msouff** [comment]
Your database is missing tables.

Try running `tethys manage makemigrations` then you can see which tables are missing with `tethys manage showmigrations` and finally apply the migrations with `tethys manage migrate`

Hopefully things work after that.

**Comment by msouff** [comment]
Also, tethys db configure is a shortcut that runs tethys db init, start, create, migrate, and createsuperuser. Your db is failing at the migrate step so after you get past that just run `tethys db createsuperuser` and your db should be good to go.
