### ISSUE TITLE
[BUG] decorator permission_required='add_dams' is not working

### ISSUE THREAD

**Issue by Sonia-96** [tethysplatform/tethys#984]
Hello,

I am working on the `dam_inventory` project from your [tutorial](http://docs.tethysplatform.org/en/stable/tutorials/key_concepts/advanced.html). For the "App Permissions" part, I created a `diviewer` without the permission to add dams. 
![image](https://github.com/tethysplatform/tethys/assets/53383436/7dcd2c6d-51ee-48e9-90af-86089b8ed82b)

And I updated the code as following:

```python
// app.py
class DamInventory(TethysAppBase):
    ...
    def permissions(self):
        """
        Define permissions for the app.
        """
        add_dams = Permission(
            name='add_dams',
            description='Add dams to inventory'
        )

        admin = PermissionGroup(
            name='admin',
            permissions=(add_dams,)
        )

        permissions = (admin,)

        return permissions
```

```python #10
// controllers.py

@controller(url='dams/add', permission_required='add_dams')
def add_dam(request):
    """
    Controller for the Add Dam page.
    """
    
    ...  # read the form and handle the errros

    context = {
        ...
        'can_add_dams': has_permission(request, 'add_dams')
    }

    return render(request, 'dam_inventory/add_dam.html', context)
```

Though the `Add Dam` button is hidden, I can still get in the `add_dam` page by entering the address `https://localhost:8000/apps/dam-inventory/dams/add` and add a new dam. So, it seems that the decorator `permission_required='add_dams'` is not working.

**Comment by msouff** [comment]
The controller parameter you need is plural `permissions_required`
