### ISSUE TITLE
[BUG] Remove References to UrlMaps in Gizmo Docs

### ISSUE THREAD

**Issue by sdc50** [tethysplatform/tethys#985]
The Select Gizmo references `UrlMaps` in the Axjax section of the docs. This should be replaced with the `controller` decorator. 

There may be other Gizmo docs that need a similar update.

**Comment by swainn** [comment]
I've addressed this for the Plotly and Bokeh gizmos as part of the docs revisions for the optional dependencies.

**Comment by sdc50** [comment]
closed by #967
